import { startEngine, stopEngine, restartEngine, isEngineRunning, getMarketTicks, getAiRecommendation, closePosition, closeAllPositions, resetAccount, getTickCount } from './engineV2';
import { getAccount, getPositions, getTrades, getPerformance, getSnapshots, getSettings, updateSettings } from './repository';
export interface ApiResult<T>{ok:boolean;data?:T;error?:string}
async function wrap<T>(fn:()=>Promise<T>):Promise<ApiResult<T>>{try{return{ok:true,data:await fn()}}catch(err){const message=err instanceof Error?err.message:'Unknown error';console.error('[api]',message);return{ok:false,error:message}}}
export async function health(){return wrap(async()=>({status:'ok',engine:isEngineRunning(),ticks:getTickCount(),db:'pglite'}))}
export async function botStatus(){return wrap(async()=>{const a=await getAccount();return{status:a.bot_status,running:a.bot_status==='RUNNING',started_at:a.started_at,uptime_seconds:a.started_at?Math.max(0,Math.round((Date.now()-new Date(a.started_at).getTime())/1000)):0,pause_until:a.pause_until,pause_reason:a.pause_reason}})}
export async function botStart(){return wrap(async()=>{const r=await startEngine();if(!r.ok)throw new Error(r.message);return{message:r.message}})}
export async function botStop(){return wrap(async()=>{const r=await stopEngine();if(!r.ok)throw new Error(r.message);return{message:r.message}})}
export async function botRestart(){return wrap(async()=>{const r=await restartEngine();if(!r.ok)throw new Error(r.message);return{message:r.message}})}
export async function portfolio():Promise<ApiResult<{cash:number;equity:number;total_pnl:number;realized_pnl:number;unrealized_pnl:number;open_value:number;open_positions:number;closed_trades:number;bot_status:string;started_at:string|null;pause_until:string|null;pause_reason:string|null}>>{return wrap(async()=>{const a=await getAccount(),p=await getPositions(),t=await getTrades(1000);return{cash:a.cash,equity:a.equity,total_pnl:a.total_pnl,realized_pnl:a.realized_pnl,unrealized_pnl:p.reduce((x,v)=>x+v.unrealized_pnl,0),open_value:p.reduce((x,v)=>x+v.notional,0),open_positions:p.length,closed_trades:t.length,bot_status:a.bot_status,started_at:a.started_at,pause_until:a.pause_until,pause_reason:a.pause_reason}})}
export async function positions(){return wrap(async()=>getPositions())}export async function trades(){return wrap(async()=>getTrades(500))}export async function performance(){return wrap(async()=>getPerformance())}export async function snapshots(){return wrap(async()=>getSnapshots(500))}export async function market(){return wrap(async()=>getMarketTicks())}export async function aiRecommendation(symbol?:string){return wrap(async()=>getAiRecommendation(symbol))}
export async function closePositionApi(id:string){return wrap(async()=>{const r=await closePosition(id);if(!r.ok)throw new Error(r.message);return{message:r.message}})}
export async function closeAllApi(){return wrap(async()=>{const r=await closeAllPositions();if(!r.ok)throw new Error(r.message);return{message:r.message}})}
export async function resetApi(){return wrap(async()=>{const r=await resetAccount();if(!r.ok)throw new Error(r.message);return{message:r.message}})}
export async function getSettingsApi(){return wrap(async()=>getSettings())}export async function updateSettingsApi(s:Partial<import('./types').Settings>){return wrap(async()=>updateSettings(s))}
