export type Candle={openTime:number;open:number;high:number;low:number;close:number;volume:number};
export type BacktestConfig={initialCapital:number;feeBps:number;slippageBps:number;riskPerTradePct:number;maxPositionPct:number;leverage:number;stopAtr:number;rewardRisk?:number;maxBarsInTrade:number};
export type StrategyResult={id:string;name:string;trades:number;wins:number;losses:number;winRate:number;profitFactor:number;netPnl:number;returnPct:number;maxDrawdownPct:number;avgTrade:number;score:number;tradeReturnsPct:number[];sharpe:number;sortino:number;calmar:number;expectancy:number;turnoverPct:number};
export type FoldDiagnostic={fold:number;startBar:number;endBar:number;trades:number;winRate:number;profitFactor:number;returnPct:number;maxDrawdownPct:number;passesTrades:boolean;passesReturn:boolean;passesProfitFactor:boolean;passesDrawdown:boolean;passed:boolean};
export type ValidationGate={status:'VALIDATED'|'REJECTED';reasons:string[];minimumTestTrades:number;minimumProfitFactor:number;minimumTestReturnPct:number;maximumTestDrawdownPct:number;maximumMonteCarloLossProbability:number};
export interface FunnelCounters{barsEvaluated:number;insufficientHistory:number;noLocalPattern:number;rejectedMomentum:number;rejectedHtf:number;rejectedScore:number;rejectedStructuralStop:number;rejectedRiskFloor:number;rejectedPathCapacity:number;tradesOpened:number;familyCandidatesTrend:number;familyCandidatesBreakout:number;familyCandidatesRetest:number;familyCandidatesCompression:number;familyCandidatesReversion:number;}
export function newFunnelCounters():FunnelCounters{return{barsEvaluated:0,insufficientHistory:0,noLocalPattern:0,rejectedMomentum:0,rejectedHtf:0,rejectedScore:0,rejectedStructuralStop:0,rejectedRiskFloor:0,rejectedPathCapacity:0,tradesOpened:0,familyCandidatesTrend:0,familyCandidatesBreakout:0,familyCandidatesRetest:0,familyCandidatesCompression:0,familyCandidatesReversion:0};}
export interface FamilyPerformance{trades:number;wins:number;winRate:number;profitFactor:number;returnPct:number;avgTrade:number;}
export type ValidationReport={symbol:string;interval:string;candles:number;dataQuality:{startTime:number;endTime:number;durationDays:number;expectedIntervalMinutes:number;gaps:number;duplicateTimestamps:number};costs:{feeBps:number;slippageBps:number;roundTripPct:number};strategies:StrategyResult[];walkForward:{trainBars:number;validationBars:number;testBars:number;selectedStrategy:string;validation:StrategyResult|null;test:StrategyResult|null};foldDiagnostics:Record<string,FoldDiagnostic[]>;monteCarlo:{simulations:number;probabilityOfLoss:number;medianReturnPct:number;p05ReturnPct:number;p95MaxDrawdownPct:number};gate:ValidationGate;generatedAt:string;research:{asOf:string;dataWindowBars:number;selectionMethod:string;coverage:string[]};signalFunnel?:FunnelCounters;familyPerformance?:Record<string,FamilyPerformance>};
export const MAX_STRATEGIES=17,MAX_HISTORY_BARS=60000;
const MIN_HISTORY=20000;
function intervalMs(interval:string){const m=interval.match(/^(\d+)([mhdw])$/i);if(!m)throw new Error(`Unsupported interval: ${interval}`);const n=Number(m[1]),u=m[2].toLowerCase();return n*(u==='m'?60000:u==='h'?3600000:u==='d'?86400000:604800000);}
function normalizeRows(rows:unknown[][],interval:string,target:number):Candle[]{const ms=intervalMs(interval),now=Date.now(),seen=new Set<number>();return rows.map(r=>({openTime:Number(r?.[0]),open:Number(r?.[1]),high:Number(r?.[2]),low:Number(r?.[3]),close:Number(r?.[4]),volume:Number(r?.[5])})).filter(c=>[c.openTime,c.open,c.high,c.low,c.close,c.volume].every(Number.isFinite)&&c.openTime+ms<=now&&!seen.has(c.openTime)&&seen.add(c.openTime)).sort((a,b)=>a.openTime-b.openTime).slice(-target);}
async function fetchViaProxy(symbol:string,interval:string,total:number):Promise<Candle[]>{const url=`/api/binance-universe?kind=history&symbol=${encodeURIComponent(symbol)}&interval=${encodeURIComponent(interval)}&total=${total}`;const res=await fetch(url,{headers:{accept:'application/json'},cache:'no-store'});if(!res.ok)throw new Error(`Historical proxy request failed (${res.status}).`);const body=await res.json() as {ok?:boolean;error?:string;klines?:unknown[][]};if(!body.ok||!Array.isArray(body.klines))throw new Error(body.error??'Historical proxy returned invalid data.');const candles=normalizeRows(body.klines,interval,total);if(candles.length<total)throw new Error(`Historical proxy returned ${candles.length.toLocaleString()} completed candles; expected ${total.toLocaleString()}.`);return candles;}
async function fetchDirect(symbol:string,interval:string,total:number):Promise<Candle[]>{const ms=intervalMs(interval),rows:unknown[][]=[];const rawTarget=total+1;let cursor=Math.max(0,Date.now()-rawTarget*ms);while(rows.length<rawTarget){const n=Math.min(1000,rawTarget-rows.length);const params=new URLSearchParams({symbol,interval,startTime:String(cursor),limit:String(n)});const res=await fetch(`https://data-api.binance.vision/api/v3/klines?${params.toString()}`,{headers:{accept:'application/json'},cache:'no-store'});if(!res.ok)throw new Error(`Historical market data request failed (${res.status}).`);const batch=await res.json() as unknown[][];if(!batch.length)break;rows.push(...batch);const last=Number(batch[batch.length-1]?.[0]);if(!Number.isFinite(last))break;cursor=last+ms;if(batch.length<n)break;await new Promise(r=>setTimeout(r,80));}const candles=normalizeRows(rows,interval,total);if(candles.length<total)throw new Error(`Historical market data returned ${candles.length.toLocaleString()} completed candles; expected ${total.toLocaleString()}.`);return candles;}
export async function fetchHistoricalCandles(symbol='BTCUSDT',interval='5m',limit=MAX_HISTORY_BARS):Promise<Candle[]>{const target=Math.min(MAX_HISTORY_BARS,Math.max(MIN_HISTORY,limit));try{return await fetchViaProxy(symbol,interval,target);}catch(proxyError){console.warn('[backtestV6] proxy history fetch failed; using direct fallback',proxyError);return fetchDirect(symbol,interval,target);}}
