import { runValidation as runV8 } from './backtestV8';
import { fetchHistoricalCandles, type Candle } from './backtestV6';
import type { BacktestConfig, ValidationReport, FoldDiagnostic } from './backtestV6';

/** V14: fast, safety-aligned validation. */
const PROFILES = [
  { rewardRisk: 1.8, stopAtr: 1.25, maxBarsInTrade: 48 },
  { rewardRisk: 2.2, stopAtr: 1.25, maxBarsInTrade: 48 },
  { rewardRisk: 2.6, stopAtr: 1.50, maxBarsInTrade: 48 },
  { rewardRisk: 3.0, stopAtr: 1.75, maxBarsInTrade: 48 },
  { rewardRisk: 2.2, stopAtr: 1.50, maxBarsInTrade: 72 },
  { rewardRisk: 3.2, stopAtr: 1.75, maxBarsInTrade: 72 },
] as const;
const MAX_HISTORY_BARS = 20000;
const VALIDATED_STRATEGY_ID = 'production';
const MIN_PF = 1.05;
const MAX_DD = 20;
const MIN_RETURN = 0;

type Candidate = { reportIndex: number; strategyId: string };
function minFoldTrades(report: ValidationReport): number { const foldSize = report.walkForward.trainBars || 0; return Math.max(12, Math.min(30, Math.floor(foldSize / 400))); }
function foldsFor(report: ValidationReport, strategyId: string): FoldDiagnostic[] { const direct = report.foldDiagnostics?.[strategyId]; if (Array.isArray(direct)) return direct; const strategy = report.strategies.find((s) => s.id === strategyId); if (!strategy) return []; const byName = report.foldDiagnostics?.[strategy.name]; return Array.isArray(byName) ? byName : []; }
function passesFold(report: ValidationReport, fold: FoldDiagnostic): boolean { const minimumTrades = minFoldTrades(report); return fold.trades >= minimumTrades && fold.returnPct > MIN_RETURN && fold.profitFactor >= MIN_PF && fold.maxDrawdownPct <= MAX_DD; }
function stabilityScore(report: ValidationReport, folds: FoldDiagnostic[]): number { if (folds.length !== 3 || !folds.every((f) => passesFold(report, f))) return -Infinity; const weights=[0.25,0.30,0.45],weighted=(selector:(f:FoldDiagnostic)=>number)=>folds.reduce((sum,f,i)=>sum+selector(f)*weights[i],0),pf=folds.map(f=>Math.min(f.profitFactor,3)),ret=folds.map(f=>f.returnPct),dd=folds.map(f=>f.maxDrawdownPct),trades=folds.map(f=>f.trades),mean=(xs:number[])=>xs.reduce((a,b)=>a+b,0)/xs.length,min=(xs:number[])=>Math.min(...xs),max=(xs:number[])=>Math.max(...xs),minimumTrades=minFoldTrades(report),meanPf=mean(pf),worstPf=min(pf),meanRet=mean(ret),worstRet=min(ret),worstDd=max(dd),meanTrades=mean(trades); return worstRet*5+worstPf*30+meanPf*10+weighted(f=>Math.min(f.profitFactor,3))*18+meanRet+weighted(f=>f.returnPct)*2+Math.min(meanTrades/Math.max(minimumTrades,1),4)*1.5+Math.min(weighted(f=>f.trades)/Math.max(minimumTrades,1),4)-worstDd*.9-weighted(f=>f.maxDrawdownPct)*.35-(max(ret)-min(ret))*.55-(max(dd)-min(dd))*.20; }
function chooseCandidate(reports: ValidationReport[]): Candidate | null { let best: (Candidate & {score:number}) | null=null; reports.forEach((report,reportIndex)=>{ if(!report.strategies.some(s=>s.id===VALIDATED_STRATEGY_ID)) return; const score=stabilityScore(report,foldsFor(report,VALIDATED_STRATEGY_ID)); if(Number.isFinite(score)&&(!best||score>best.score)) best={reportIndex,strategyId:VALIDATED_STRATEGY_ID,score}; }); return best?{reportIndex:best.reportIndex,strategyId:best.strategyId}:null; }
function diagnosticReason(reports: ValidationReport[]): string { let best:{report:ValidationReport;strategy:string;passed:number;score:number}|null=null; for(const report of reports){const strategy=report.strategies.find(s=>s.id===VALIDATED_STRATEGY_ID);if(!strategy)continue;const folds=foldsFor(report,VALIDATED_STRATEGY_ID);if(folds.length!==3)continue;const passed=folds.filter(f=>passesFold(report,f)).length,score=folds.reduce((sum,f,i)=>sum+[.25,.30,.45][i]*(Math.min(f.profitFactor,3)*10+f.returnPct*2-f.maxDrawdownPct*.35),0);if(!best||passed>best.passed||(passed===best.passed&&score>best.score))best={report,strategy:strategy.name,passed,score};} if(!best)return 'Production Regime Breakout v13 did not produce complete pre-OOS fold diagnostics.'; return `Production Regime Breakout v13 did not pass all 3 pre-OOS stability folds (${best.passed}/3 passed; minimum ${minFoldTrades(best.report)} trades/fold, PF >= ${MIN_PF}, positive return, DD <= ${MAX_DD}%). Other research strategies cannot approve the paper bot unless the engine is explicitly wired to trade the same validated strategy.`; }
async function runProfile(symbol:string,interval:string,cfg:Partial<BacktestConfig>,profile:typeof PROFILES[number],candles:Candle[],selectedStrategyId?:string,preOosOnly=false){ return runV8(symbol,interval,{...cfg,rewardRisk:profile.rewardRisk,stopAtr:profile.stopAtr,maxBarsInTrade:profile.maxBarsInTrade},selectedStrategyId,candles,preOosOnly); }
export async function runValidation(symbol='BTCUSDT',interval='1h',cfg:Partial<BacktestConfig>={},selectedStrategyId?:string):Promise<ValidationReport>{ const candles=await fetchHistoricalCandles(symbol,interval,MAX_HISTORY_BARS);if(candles.length<20000)throw new Error(`Need 20,000 completed candles; received ${candles.length}.`);if(selectedStrategyId)return runProfile(symbol,interval,cfg,PROFILES[1],candles,selectedStrategyId,false);const scout=await runV8(symbol,interval,cfg,undefined,candles,true),reports:ValidationReport[]=[];for(const profile of PROFILES)reports.push(await runProfile(symbol,interval,cfg,profile,candles,VALIDATED_STRATEGY_ID,true));const candidate=chooseCandidate(reports);if(!candidate){const diagnostic={...scout};return{...diagnostic,walkForward:{...diagnostic.walkForward,selectedStrategy:'',validation:null,test:null},gate:{...diagnostic.gate,status:'REJECTED',reasons:[diagnosticReason(reports)]},research:{...diagnostic.research,selectionMethod:'6 exit profiles for the exact paper-engine strategy; three non-overlapping pre-OOS folds; all 3 folds required; recent-fold weighted robustness; fold-dispersion penalties; untouched 30% OOS; costs included in every trade.',coverage:[...diagnostic.research.coverage,'6-profile multi-horizon exit sweep','paper-engine/validator strategy alignment','recent pre-OOS regime weighting','fold return/drawdown dispersion penalty','three-fold regime consistency gate']}};}const c= candidate as any; return runProfile(symbol,interval,cfg,PROFILES[c.reportIndex],candles,c.strategyId,false); }
export * from './backtestV8';
