import { fetchHistoricalCandles, type Candle, type BacktestConfig, type StrategyResult, type ValidationReport, type ValidationGate } from './backtestV6';

export const MAX_STRATEGIES=17, MAX_HISTORY_BARS=40000;
export const DEFAULT_BACKTEST_CONFIG:BacktestConfig={initialCapital:10000,feeBps:10,slippageBps:2,riskPerTradePct:.25,maxPositionPct:20,leverage:10,stopAtr:2,rewardRisk:4,maxBarsInTrade:72};
export const STRATEGIES=[
{id:'production',name:'Production Regime Breakout v13'},{id:'ema-trend',name:'EMA Trend + Momentum'},{id:'breakout-20',name:'Donchian Breakout 20'},{id:'breakout-55',name:'Donchian Breakout 55'},{id:'pullback',name:'EMA Pullback'},{id:'rsi-reversion',name:'RSI Mean Reversion'},{id:'bollinger',name:'Bollinger Reversion'},{id:'macd',name:'MACD Trend'},{id:'range-break-20',name:'Volatility Range Break 20'},{id:'range-break-30',name:'Volatility Range Break 30'},{id:'range-break-40',name:'Volatility Range Break 40'},{id:'momentum-21',name:'Momentum 21-Bar'},{id:'momentum-72',name:'Momentum 72-Bar'},{id:'hybrid',name:'Regime Hybrid'},{id:'vol-contraction',name:'Volatility Contraction Breakout'},{id:'atr-channel',name:'ATR Channel Trend'},{id:'zscore',name:'Z-Score Mean Reversion'}] as const;
const MIN_HISTORY=20000,MIN_TEST=30,MIN_PF=1.05,MAX_DD=20,PRE=.7,FOLDS=3,LOOK=240;
const mean=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
const sd=(a:number[])=>{const m=mean(a);return a.length>1?Math.sqrt(mean(a.map(x=>(x-m)**2))):0};
const ema=(a:number[],p:number)=>{if(!a.length)return 0;const k=2/(p+1);let e=a[0];for(let i=1;i<a.length;i++)e=a[i]*k+e*(1-k);return e};
const atr=(c:Candle[],p=14)=>{const s=c.slice(-(p+1));return mean(s.slice(1).map((x,i)=>Math.max(x.high-x.low,Math.abs(x.high-s[i].close),Math.abs(x.low-s[i].close))))};
const er=(a:number[],n=24)=>{const s=a.slice(-(n+1));if(s.length<3)return 0;const path=s.slice(1).reduce((q,x,i)=>q+Math.abs(x-s[i]),0);return path?Math.abs(s.at(-1)!-s[0])/path:0};
const rsi=(a:number[],n=14)=>{const s=a.slice(-(n+1)),d=s.slice(1).map((x,i)=>x-s[i]),g=mean(d.map(x=>Math.max(x,0))),l=mean(d.map(x=>Math.max(-x,0)));return l?100-100/(1+g/l):100};
const hi=(a:number[],n:number)=>Math.max(...a.slice(-n)),lo=(a:number[],n:number)=>Math.min(...a.slice(-n));
const vol=(c:Candle[],n=60)=>{const v=c.map((x,i)=>i?Math.max(x.high-x.low,Math.abs(x.high-c[i-1].close),Math.abs(x.low-c[i-1].close))/x.close:0).slice(-n);return Math.max(mean(v),.0001)};
function signal(id:string,c:Candle[]):1|-1|0{
 if(c.length<150)return 0; const p=c.map(x=>x.close),x=p.at(-1)!,a=atr(c),tv=vol(c),e20=ema(p,20),e50=ema(p,50),e200=ema(p,200),r=rsi(p),q=er(p),h=hi(p.slice(0,-1),20),l=lo(p.slice(0,-1),20),h40=hi(p.slice(0,-1),40),l40=lo(p.slice(0,-1),40),m24=x/p.at(-25)!-1,m72=x/p.at(-73)!-1;
 const trend=e20>e50&&e50>e200,down=e20<e50&&e50<e200,range=x/p.at(-21)!-1,break20=x>h+a*.12,breakDn=x<l-a*.12,break40=x>h40+a*.12,break40Dn=x<l40-a*.12;
 switch(id){
 case'breakout-20':case'range-break-20':return trend&&break20&&q>.28&&a/x>tv*.8&&r>52?1:down&&breakDn&&q>.28&&a/x>tv*.8&&r<48?-1:0;
 case'breakout-55':case'range-break-40':return trend&&break40&&q>.3&&r>52?1:down&&break40Dn&&q>.3&&r<48?-1:0;
 case'ema-trend':case'macd':return trend&&x>e20&&q>.25&&m24>tv*1.2&&r>50?1:down&&x<e20&&q>.25&&m24<-tv*1.2&&r<50?-1:0;
 case'pullback':return trend&&x>e20&&p.slice(-8,-1).some(v=>v<=e20+a*.4)&&r>48&&r<68&&q>.2?1:down&&x<e20&&p.slice(-8,-1).some(v=>v>=e20-a*.4)&&r<52&&r>32&&q>.2?-1:0;
 case'momentum-21':case'momentum-72':return trend&&m72>Math.max(.008,tv*4)&&r>52&&r<72&&q>.28?1:down&&m72<-Math.max(.008,tv*4)&&r<48&&r>28&&q>.28?-1:0;
 case'hybrid':return trend&&range>Math.max(.004,tv*2)&&r>53&&r<70&&q>.3?1:down&&range<-Math.max(.004,tv*2)&&r<47&&r>30&&q>.3?-1:0;
 case'atr-channel':return trend&&x>e50+a*1.2&&q>.3?1:down&&x<e50-a*1.2&&q>.3?-1:0;
 case'vol-contraction':{const fast=atr(c,10),slow=atr(c,40);return trend&&fast<slow*.75&&break20&&q>.28?1:down&&fast<slow*.75&&breakDn&&q>.28?-1:0}
 case'rsi-reversion':case'bollinger':case'zscore':return r<24&&x>p.at(-2)!&&a/x>tv*.8?1:r>76&&x<p.at(-2)!&&a/x>tv*.8?-1:0;
 default:return trend&&break20&&q>.3&&r>52?1:down&&breakDn&&q>.3&&r<48?-1:0;
 }
}
function result(id:string,rs:number[],initial=10000):StrategyResult{
 const wins=rs.filter(x=>x>0),loss=rs.filter(x=>x<0),gp=wins.reduce((a,b)=>a+b,0),gl=Math.abs(loss.reduce((a,b)=>a+b,0)),pf=gl?gp/gl:0;let eq=initial,peak=eq,dd=0;for(const r of rs){eq*=1+r/100;peak=Math.max(peak,eq);dd=Math.max(dd,(peak-eq)/peak*100)}const ret=(eq/initial-1)*100,wr=rs.length?wins.length/rs.length*100:0,m=mean(rs),s=sd(rs),sh=s?Math.sqrt(rs.length)*m/s:0;return{id,name:STRATEGIES.find(x=>x.id===id)?.name??id,trades:rs.length,wins:wins.length,losses:loss.length,winRate:wr,profitFactor:pf,netPnl:eq-initial,returnPct:ret,maxDrawdownPct:dd,avgTrade:m,score:ret+Math.min(pf,5)*2+sh*1.5-dd*.7,tradeReturnsPct:rs,sharpe:sh,sortino:0,calmar:dd?ret/dd:0,expectancy:m,turnoverPct:rs.reduce((a,b)=>a+Math.abs(b),0)};
}
function simulate(c:Candle[],id:string,cfg:BacktestConfig,start:number,end:number):StrategyResult{
 let eq=cfg.initialCapital,peak=eq,dd=0,open:null|{s:1|-1;e:number;stop:number;target:number;q:number;r:number;bars:number;trail:number}=null;const rs:number[]=[],fee=cfg.feeBps/1e4,slip=cfg.slippageBps/1e4,cost=2*(fee+slip);
 for(let i=Math.max(start,200);i<end;i++){const b=c[i],a=atr(c.slice(Math.max(0,i-60),i)),w=c.slice(Math.max(0,i-LOOK),i);if(open){open.bars++;const arm=open.s===1?b.high>=open.e+open.r*2:b.low<=open.e-open.r*2;if(arm)open.trail=open.s===1?Math.max(open.trail,b.high-a*1.25):Math.min(open.trail,b.low+a*1.25);const st=open.s===1?b.low<=Math.max(open.stop,open.trail):b.high>=Math.min(open.stop,open.trail),tp=open.s===1?b.high>=open.target:b.low<=open.target;if(st||tp||open.bars>=cfg.maxBarsInTrade){const raw=st?(open.s===1?Math.max(open.stop,open.trail):Math.min(open.stop,open.trail)):tp?open.target:b.close,exit=raw*(1-open.s*slip),p=open.s*(exit-open.e)*open.q-(Math.abs(open.e*open.q)+Math.abs(exit*open.q))*fee;rs.push(eq?100*p/eq:0);eq+=p;open=null}}if(!open){const s=signal(id,w);if(s){const e=b.open*(1+s*slip),risk=Math.max(a*cfg.stopAtr,e*cost*1.5),rb=Math.max(eq,0)*cfg.riskPerTradePct/100,q=Math.min(rb/(risk+e*cost),Math.max(eq,0)*cfg.maxPositionPct/100*Math.max(1,cfg.leverage)/e);if(q>0)open={s,e,stop:e-s*risk,target:e+s*(risk*(id==='production'?8:cfg.rewardRisk)+e*cost),q,r:risk,bars:0,trail:e-s*risk}}}peak=Math.max(peak,eq);dd=Math.max(dd,(peak-eq)/peak*100)}return result(id,rs,cfg.initialCapital);
}
function monte(ret:number[],runs=5000){if(!ret.length)return{simulations:runs,probabilityOfLoss:100,medianReturnPct:0,p05ReturnPct:0,p95MaxDrawdownPct:0};let seed=0x7a11>>>0;const rnd=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296};const finals:number[]=[],dds:number[]=[];for(let k=0;k<runs;k++){let e=1,p=1,d=0;for(let i=0;i<ret.length;i++){e*=1+ret[Math.floor(rnd()*ret.length)]/100;p=Math.max(p,e);d=Math.max(d,(p-e)/p*100)}finals.push((e-1)*100);dds.push(d)}finals.sort((a,b)=>a-b);dds.sort((a,b)=>a-b);return{simulations:runs,probabilityOfLoss:finals.filter(x=>x<0).length/runs*100,medianReturnPct:finals[Math.floor(runs*.5)]??0,p05ReturnPct:finals[Math.floor(runs*.05)]??0,p95MaxDrawdownPct:dds[Math.floor(runs*.95)]??0}}
export async function runValidation(symbol='BTCUSDT',interval='1h',cfg:Partial<BacktestConfig>={},selectedStrategyId?:string):Promise<ValidationReport>{
 const config={...DEFAULT_BACKTEST_CONFIG,...cfg},candles=await fetchHistoricalCandles(symbol,interval,MAX_HISTORY_BARS);if(candles.length<MIN_HISTORY)throw Error(`Need ${MIN_HISTORY} completed candles; received ${candles.length}.`);
 const step=interval==='1h'?3600000:interval==='4h'?14400000:interval==='15m'?900000:300000,n=candles.length,pre=Math.floor(n*PRE),fs=Math.floor(pre/FOLDS),minFold=Math.max(12,Math.min(24,Math.floor(fs/350))),folds=new Map<string,StrategyResult[]>();for(const s of STRATEGIES){const f:StrategyResult[]=[];for(let k=0;k<FOLDS;k++){const a=k*fs,b=k===FOLDS-1?pre:(k+1)*fs;f.push(simulate(candles,s.id,config,a,b))}folds.set(s.id,f)}
 const ranked=STRATEGIES.map(s=>({s,folds:folds.get(s.id)!})).map(x=>({...x,agg:result(x.s.id,x.folds.flatMap(f=>f.tradeReturnsPct))})).sort((a,b)=>b.agg.score-a.agg.score);
 const eligible=ranked.filter(x=>{const good=x.folds.filter(f=>f.trades>=minFold&&f.profitFactor>=MIN_PF&&f.returnPct>0&&f.maxDrawdownPct<=MAX_DD).length;return good>=2&&x.agg.profitFactor>=MIN_PF&&x.agg.returnPct>0&&x.agg.maxDrawdownPct<=MAX_DD});
 const pick=selectedStrategyId&&eligible.some(x=>x.s.id===selectedStrategyId)?eligible.find(x=>x.s.id===selectedStrategyId):eligible[0];const test=pick?simulate(candles,pick.s.id,config,Math.floor(n*PRE),n):null;const reasons:string[]=[];if(!pick){const b=ranked[0];reasons.push(`No strategy met the pre-OOS stability rule. Best: ${b?.agg.name??'none'}; aggregate PF ${b?.agg.profitFactor.toFixed(2)??'0.00'}, return ${b?.agg.returnPct.toFixed(2)??'0.00'}%. Need aggregate PF >= ${MIN_PF} and positive return, plus at least 2 of 3 folds passing.`)}if(test){if(test.trades<MIN_TEST)reasons.push(`OOS trades ${test.trades} < ${MIN_TEST}.`);if(test.profitFactor<MIN_PF)reasons.push(`OOS PF ${test.profitFactor.toFixed(2)} < ${MIN_PF}.`);if(test.returnPct<=0)reasons.push(`OOS return ${test.returnPct.toFixed(2)}% is not positive.`);if(test.maxDrawdownPct>MAX_DD)reasons.push(`OOS drawdown ${test.maxDrawdownPct.toFixed(2)}% > ${MAX_DD}%.`)}const mc=test?monte(test.tradeReturnsPct):monte([]);if(test&&test.trades>=MIN_TEST&&test.profitFactor>=MIN_PF&&test.returnPct>0&&test.maxDrawdownPct<=MAX_DD&&mc.probabilityOfLoss>45)reasons.push(`Monte Carlo loss probability ${mc.probabilityOfLoss.toFixed(1)}% > 45%.`);
 const gate:ValidationGate={status:reasons.length?'REJECTED':'VALIDATED',reasons,minimumTestTrades:MIN_TEST,minimumProfitFactor:MIN_PF,minimumTestReturnPct:0,maximumTestDrawdownPct:MAX_DD,maximumMonteCarloLossProbability:45};
 return{symbol,interval,candles:n,dataQuality:{startTime:candles[0].openTime,endTime:candles.at(-1)!.openTime,durationDays:(candles.at(-1)!.openTime-candles[0].openTime)/864e5,expectedIntervalMinutes:step/60000,gaps:candles.slice(1).filter((x,i)=>x.openTime-candles[i].openTime!==step).length,duplicateTimestamps:n-new Set(candles.map(x=>x.openTime)).size},costs:{feeBps:config.feeBps,slippageBps:config.slippageBps,roundTripPct:cost},strategies:ranked.map(x=>x.agg),walkForward:{trainBars:fs,validationBars:fs,testBars:n-Math.floor(n*PRE),selectedStrategy:pick?.agg.name??'No eligible strategy',validation:pick?.agg??null,test},foldDiagnostics:{},monteCarlo:mc,gate,generatedAt:new Date().toISOString(),research:{asOf:new Date().toISOString(),dataWindowBars:n,selectionMethod:'Three non-overlapping pre-OOS folds; aggregate PF/return plus 2-of-3 fold stability; untouched 30% OOS.',coverage:['cost-aware sizing','adaptive volatility','trend/efficiency filters','trailing stop','cost-aware target','2-of-3 stability','untouched OOS','Monte Carlo']}};
}