import { evaluateProductionStrategy } from './strategy';

export type Candle={openTime:number;open:number;high:number;low:number;close:number;volume:number};
export type BacktestConfig={initialCapital:number;feeBps:number;slippageBps:number;riskPerTradePct:number;maxPositionPct:number;leverage:number;stopAtr:number;rewardRisk:number;maxBarsInTrade:number};
export type StrategyResult={id:string;name:string;trades:number;wins:number;losses:number;winRate:number;profitFactor:number;netPnl:number;returnPct:number;maxDrawdownPct:number;avgTrade:number;score:number;tradeReturnsPct:number[];sharpe:number;sortino:number;calmar:number;expectancy:number;turnoverPct:number};
export type FoldDiagnostic={fold:number;startBar:number;endBar:number;trades:number;winRate:number;profitFactor:number;returnPct:number;maxDrawdownPct:number;passesTrades:boolean;passesReturn:boolean;passesProfitFactor:boolean;passesDrawdown:boolean;passed:boolean};
export type ValidationGate={status:'VALIDATED'|'REJECTED';reasons:string[];minimumTestTrades:number;minimumProfitFactor:number;minimumTestReturnPct:number;maximumTestDrawdownPct:number;maximumMonteCarloLossProbability:number};
export type ValidationReport={symbol:string;interval:string;candles:number;dataQuality:{startTime:number;endTime:number;durationDays:number;expectedIntervalMinutes:number;gaps:number;duplicateTimestamps:number};costs:{feeBps:number;slippageBps:number;roundTripPct:number};strategies:StrategyResult[];walkForward:{trainBars:number;validationBars:number;testBars:number;selectedStrategy:string;validation:StrategyResult|null;test:StrategyResult|null};foldDiagnostics:Record<string,FoldDiagnostic[]>;monteCarlo:{simulations:number;probabilityOfLoss:number;medianReturnPct:number;p05ReturnPct:number;p95MaxDrawdownPct:number};gate:ValidationGate;generatedAt:string;research:{asOf:string;dataWindowBars:number;selectionMethod:string;coverage:string[]}};

export const MAX_STRATEGIES=17,MAX_HISTORY_BARS=40000;
export const DEFAULT_BACKTEST_CONFIG:BacktestConfig={initialCapital:10000,feeBps:10,slippageBps:2,riskPerTradePct:0.25,maxPositionPct:20,leverage:10,stopAtr:2.25,rewardRisk:1.8,maxBarsInTrade:60};
export const STRATEGIES=[
{id:'production',name:'Production Regime Breakout v13'},{id:'ema-trend',name:'EMA Trend + Momentum'},{id:'breakout-20',name:'Donchian Breakout 20'},{id:'breakout-55',name:'Donchian Breakout 55'},{id:'pullback',name:'EMA Pullback'},{id:'rsi-reversion',name:'RSI Mean Reversion'},{id:'bollinger',name:'Bollinger Reversion'},{id:'macd',name:'MACD Trend'},{id:'range-break-20',name:'Volatility Range Break 20'},{id:'range-break-30',name:'Volatility Range Break 30'},{id:'range-break-40',name:'Volatility Range Break 40'},{id:'momentum-21',name:'Momentum 21-Bar'},{id:'momentum-72',name:'Momentum 72-Bar'},{id:'hybrid',name:'Regime Hybrid'},{id:'vol-contraction',name:'Volatility Contraction Breakout'},{id:'atr-channel',name:'ATR Channel Trend'},{id:'zscore',name:'Z-Score Mean Reversion'}] as const;
const MIN_HISTORY=20000,MIN_TEST=30,MIN_PF=1.05,MAX_DD=20,PRE_OOS=.70,FOLDS=3,LOOKBACK=240;
const mean=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0;
const std=(x:number[])=>{const m=mean(x);return x.length>1?Math.sqrt(mean(x.map(v=>(v-m)**2))):0};
const ema=(x:number[],p:number)=>{if(!x.length)return 0;const k=2/(p+1);let e=x[0];for(let i=1;i<x.length;i++)e=x[i]*k+e*(1-k);return e};
const atr=(c:Candle[],p=14)=>{const x=c.slice(-(p+1));return mean(x.slice(1).map((v,i)=>Math.max(v.high-v.low,Math.abs(v.high-x[i].close),Math.abs(v.low-x[i].close))))};
const typicalVol=(c:Candle[],p=80)=>{const vals:number[]=[];for(let i=Math.max(1,c.length-p);i<c.length;i++){const q=c[i],prev=c[i-1].close;vals.push(Math.max(q.high-q.low,Math.abs(q.high-prev),Math.abs(q.low-prev))/q.close)}return Math.max(mean(vals),0.0001)};
const hi=(x:number[],n:number)=>Math.max(...x.slice(-n)),lo=(x:number[],n:number)=>Math.min(...x.slice(-n));
const rsi=(x:number[],p=14)=>{const s=x.slice(-(p+1)),d=s.slice(1).map((v,i)=>v-s[i]),g=mean(d.map(v=>Math.max(v,0))),l=mean(d.map(v=>Math.max(-v,0)));return l?100-100/(1+g/l):100};
const slope=(x:number[])=>{if(x.length<2)return 0;const n=x.length,xm=(n-1)/2,ym=mean(x);let a=0,b=0;for(let i=0;i<n;i++){a+=(i-xm)*(x[i]-ym);b+=(i-xm)**2}return b?a/b:0};
const efficiency=(x:number[],n=24)=>{const s=x.slice(-(n+1));if(s.length<3)return 0;const net=Math.abs(s[s.length-1]-s[0]),path=s.slice(1).reduce((a,v,i)=>a+Math.abs(v-s[i]),0);return path?net/path:0};
const volumeRatio=(c:Candle[],n=30)=>{const last=c[c.length-1]?.volume??0,avg=mean(c.slice(-n-1,-1).map(x=>x.volume).filter(Number.isFinite));return avg>0?last/avg:1};

function signal(id:string,c:Candle[],cfg:BacktestConfig):1|-1|0{
 if(c.length<150)return 0;
 if(id==='production'){const s=evaluateProductionStrategy(c.map(x=>x.close),{minScore:72,lookback:240,feeBps:cfg.feeBps,slippageBps:cfg.slippageBps});return s.action==='LONG'?1:s.action==='SHORT'?-1:0}
 const p=c.map(x=>x.close),last=p[p.length-1],a=atr(c),v=a/last,tv=typicalVol(c),e9=ema(p,9),e20=ema(p,20),e50=ema(p,50),e100=ema(p,100),r=rsi(p),up=e20>e50&&e50>e100,down=e20<e50&&e50<e100,s12=slope(p.slice(-12))/last,s36=slope(p.slice(-36))/last,m21=last/p[Math.max(0,p.length-22)]-1,m72=last/p[Math.max(0,p.length-73)]-1,prior=p.slice(0,-1),h20=hi(prior,20),l20=lo(prior,20),h30=hi(prior,30),l30=lo(prior,30),h40=hi(prior,40),l40=lo(prior,40),h55=hi(prior,55),l55=lo(prior,55),mid=mean(p.slice(-20)),sd=std(p.slice(-20)),upper=mid+2*sd,lower=mid-2*sd,macd=ema(p,12)-ema(p,26),macdPrev=ema(p.slice(0,-1),12)-ema(p.slice(0,-1),26),af=atr(c,10),as=atr(c,40),er=efficiency(p,24),vr=volumeRatio(c),contract=af>0&&as>0&&af/as<.72;
 const volOk=v>=tv*.75&&v<=tv*3.5,breakBuffer=Math.max(tv*.18,0.0006)*last,notExtended=Math.abs(last-e20)<=a*2.5,volConfirm=vr>=.95;
 switch(id){
 case'ema-trend':return up&&last>e9&&s36>0&&volOk&&er>.22?1:down&&last<e9&&s36<0&&volOk&&er>.22?-1:0;
 case'breakout-20':return last>h20+breakBuffer&&up&&s12>0&&volOk&&volConfirm?1:last<l20-breakBuffer&&down&&s12<0&&volOk&&volConfirm?-1:0;
 case'breakout-55':return last>h55+breakBuffer&&up&&s36>0&&v>=tv*.8&&volConfirm?1:last<l55-breakBuffer&&down&&s36<0&&v>=tv*.8&&volConfirm?-1:0;
 case'pullback':return up&&last>e20&&p.slice(-6,-1).some(x=>x<=e20*1.002)&&r>48&&r<70&&s12>0&&er>.2?1:down&&last<e20&&p.slice(-6,-1).some(x=>x>=e20*.998)&&r<52&&r>30&&s12<0&&er>.2?-1:0;
 case'rsi-reversion':return r<26&&last>p[p.length-2]&&v>=tv*.8?1:r>74&&last<p[p.length-2]&&v>=tv*.8?-1:0;
 case'bollinger':return last<lower&&last>p[p.length-2]&&r<45?1:last>upper&&last<p[p.length-2]&&r>55?-1:0;
 case'macd':return macd>0&&macd>macdPrev&&last>e50&&volOk&&er>.2?1:macd<0&&macd<macdPrev&&last<e50&&volOk&&er>.2?-1:0;
 case'range-break-20':return last>h20+breakBuffer&&up&&v>=tv*.9?1:last<l20-breakBuffer&&down&&v>=tv*.9?-1:0;
 case'range-break-30':return last>h30+breakBuffer&&up&&v>=tv*.9&&er>.2?1:last<l30-breakBuffer&&down&&v>=tv*.9&&er>.2?-1:0;
 case'range-break-40':return last>h40+breakBuffer&&up&&v>=tv&&s12>0&&er>.25?1:last<l40-breakBuffer&&down&&v>=tv&&s12<0&&er>.25?-1:0;
 case'momentum-21':return m21>Math.max(.0025,tv*1.6)&&up&&last>e20&&r>=52&&r<=72&&er>.24&&notExtended?1:m21<-Math.max(.0025,tv*1.6)&&down&&last<e20&&r>=28&&r<=48&&er>.24&&notExtended?-1:0;
 case'momentum-72':return m72>Math.max(.006,tv*3.5)&&up&&last>e50&&r>=52&&r<=72&&er>.28&&notExtended?1:m72<-Math.max(.006,tv*3.5)&&down&&last<e50&&r>=28&&r<=48&&er>.28&&notExtended?-1:0;
 case'hybrid':return up&&m21>Math.max(.002,tv*1.5)&&r>=52&&r<=70&&er>.25&&volConfirm?1:down&&m21<-Math.max(.002,tv*1.5)&&r>=30&&r<=48&&er>.25&&volConfirm?-1:0;
 case'vol-contraction':return contract&&last>h20+breakBuffer&&up&&s12>0&&volConfirm?1:contract&&last<l20-breakBuffer&&down&&s12<0&&volConfirm?-1:0;
 case'atr-channel':{const center=ema(p,50),band=a*1.5;return last>center+band&&s36>0&&er>.25?1:last<center-band&&s36<0&&er>.25?-1:0}
 case'zscore':{const z=(last-mid)/(sd||1);return z<-2.2&&r<38&&last>p[p.length-2]&&v>=tv*.8?1:z>2.2&&r>62&&last<p[p.length-2]&&v>=tv*.8?-1:0}
 default:return 0}
}

function summarize(id:string,pnls:number[],initial:number,dd:number,returns:number[]):StrategyResult{
 const wins=pnls.filter(x=>x>0).length,losses=pnls.filter(x=>x<0).length,gp=pnls.filter(x=>x>0).reduce((a,b)=>a+b,0),gl=Math.abs(pnls.filter(x=>x<0).reduce((a,b)=>a+b,0)),pf=gl?gp/gl:0,net=pnls.reduce((a,b)=>a+b,0),ret=initial?net/initial*100:0,wr=pnls.length?wins/pnls.length*100:0,avg=pnls.length?mean(pnls):0,r=returns.map(x=>x/100),m=mean(r),s=std(r),neg=std(r.filter(x=>x<0)),sh=s?Math.sqrt(r.length)*m/s:0,so=neg?Math.sqrt(r.length)*m/neg:0,cal=dd?ret/dd:0,turn=initial?pnls.reduce((a,b)=>a+Math.abs(b),0)/initial*100:0;
 const score=(ret+Math.min(pf,5)*2.5+sh*2+so*.75+wr/25+cal*.25-dd*.8)*Math.min(1,pnls.length/30);
 return{id,name:STRATEGIES.find(s=>s.id===id)?.name??id,trades:pnls.length,wins,losses,winRate:wr,profitFactor:pf,netPnl:net,returnPct:ret,maxDrawdownPct:dd,avgTrade:avg,score,tradeReturnsPct:returns,sharpe:sh,sortino:so,calmar:cal,expectancy:avg,turnoverPct:turn};
}
function summarizeReturns(id:string,returns:number[],initial:number):StrategyResult{
 const wins=returns.filter(x=>x>0).length,losses=returns.filter(x=>x<0).length,gp=returns.filter(x=>x>0).reduce((a,b)=>a+b,0),gl=Math.abs(returns.filter(x=>x<0).reduce((a,b)=>a+b,0)),pf=gl?gp/gl:0;let eq=initial,peak=initial,dd=0;for(const r of returns){eq*=1+r/100;peak=Math.max(peak,eq);dd=Math.max(dd,peak?(peak-eq)/peak*100:0)}
 const ret=initial?(eq/initial-1)*100:0,wr=returns.length?wins/returns.length*100:0,avg=mean(returns),norm=returns.map(x=>x/100),s=std(norm),neg=std(norm.filter(x=>x<0)),sh=s?Math.sqrt(norm.length)*mean(norm)/s:0,so=neg?Math.sqrt(norm.length)*mean(norm)/neg:0,cal=dd?ret/dd:0,score=(ret+Math.min(pf,5)*2.5+sh*2+so*.75+wr/25+cal*.25-dd*.8)*Math.min(1,returns.length/30);
 return{id,name:STRATEGIES.find(s=>s.id===id)?.name??id,trades:returns.length,wins,losses,winRate:wr,profitFactor:pf,netPnl:eq-initial,returnPct:ret,maxDrawdownPct:dd,avgTrade:avg,score,tradeReturnsPct:returns,sharpe:sh,sortino:so,calmar:cal,expectancy:avg,turnoverPct:returns.reduce((a,b)=>a+Math.abs(b),0)};
}
function closePnl(raw:number,p:{side:1|-1;entry:number;qty:number},fee:number,slip:number){const exit=raw*(1-p.side*slip),gross=p.side*(exit-p.entry)*p.qty,fees=(Math.abs(p.entry*p.qty)+Math.abs(exit*p.qty))*fee;return gross-fees}
function simulate(c:Candle[],id:string,cfg:BacktestConfig,start:number,end:number):StrategyResult{
 let equity=cfg.initialCapital,peak=equity,maxDd=0;const pnls:number[]=[],rets:number[]=[];let open:{side:1|-1;entry:number;stop:number;target:number;qty:number;bars:number}|null=null;const fee=cfg.feeBps/10000,slip=cfg.slippageBps/10000,roundTripPct=2*fee+2*slip,MIN_R_OVER_COST=1.5;
 for(let i=Math.max(150,start);i<end;i++){
  const bar=c[i];let closed=false;
  if(open){open.bars++;const stop=open.side===1?bar.low<=open.stop:bar.high>=open.stop,tp=open.side===1?bar.high>=open.target:bar.low<=open.target;if(stop||tp||open.bars>=cfg.maxBarsInTrade){const raw=stop?open.stop:tp?open.target:bar.close,pnl=closePnl(raw,open,fee,slip);rets.push(equity?100*pnl/equity:0);pnls.push(pnl);equity+=pnl;open=null;closed=true}}
  if(!open&&!closed){const w=c.slice(Math.max(0,i-LOOKBACK),i),side=signal(id,w,cfg);if(side){const entry=bar.open*(1+side*slip),risk=Math.max(atr(w)*cfg.stopAtr,entry*roundTripPct*MIN_R_OVER_COST),rr=id==='production'?1.8:cfg.rewardRisk,stop=entry-side*risk,target=entry+side*(risk*rr+entry*roundTripPct),riskBudget=Math.max(0,equity)*cfg.riskPerTradePct/100,riskQty=(risk+entry*roundTripPct)>0?riskBudget/(risk+entry*roundTripPct):0,maxNotional=Math.max(0,equity)*cfg.maxPositionPct/100*Math.max(1,cfg.leverage),qty=Math.min(riskQty,maxNotional/entry);if(qty>0)open={side,entry,stop,target,qty,bars:0}}}
  peak=Math.max(peak,equity);maxDd=Math.max(maxDd,peak?(peak-equity)/peak*100:0)
 }
 if(open){const pnl=closePnl(c[end-1].close,open,fee,slip);rets.push(equity?100*pnl/equity:0);pnls.push(pnl);equity+=pnl}
 return summarize(id,pnls,cfg.initialCapital,maxDd,rets);
}
function intervalMs(interval:string){const m=interval.match(/^(\d+)([mhdw])$/i);if(!m)throw new Error(`Unsupported interval: ${interval}`);const n=Number(m[1]),u=m[2].toLowerCase();return n*(u==='m'?60000:u==='h'?3600000:u==='d'?86400000:604800000)}
export async function fetchHistoricalCandles(symbol='BTCUSDT',interval='1h',limit=MAX_HISTORY_BARS):Promise<Candle[]>{const target=Math.min(MAX_HISTORY_BARS,Math.max(MIN_HISTORY,limit)),ms=intervalMs(interval),start=Math.max(0,Date.now()-target*ms),rows:unknown[][]=[];let cursor=start;while(rows.length<target){const n=Math.min(1000,target-rows.length),url=`https://data-api.binance.vision/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=${encodeURIComponent(interval)}&startTime=${cursor}&limit=${n}`,res=await fetch(url,{headers:{Accept:'application/json'}});if(!res.ok)throw new Error(`Historical market data request failed (${res.status}).`);const batch=await res.json() as unknown[][];if(!batch.length)break;rows.push(...batch);const last=Number(batch[batch.length-1]?.[0]);if(!Number.isFinite(last))break;cursor=last+ms;if(batch.length<n)break;await new Promise(r=>setTimeout(r,50))}const seen=new Set<number>(),now=Date.now();return rows.map(r=>({openTime:Number(r[0]),open:Number(r[1]),high:Number(r[2]),low:Number(r[3]),close:Number(r[4]),volume:Number(r[5])})).filter(c=>[c.openTime,c.open,c.high,c.low,c.close,c.volume].every(Number.isFinite)&&c.openTime+ms<=now&&!seen.has(c.openTime)&&seen.add(c.openTime)).sort((a,b)=>a.openTime-b.openTime).slice(-target)}
function mc(ret:number[],runs=5000,seed=0x7a11){if(!ret.length)return{simulations:runs,probabilityOfLoss:100,medianReturnPct:0,p05ReturnPct:0,p95MaxDrawdownPct:0};let s=seed>>>0;const rnd=()=>{s=(1664525*s+1013904223)>>>0;return s/4294967296};const finals:number[]=[],dds:number[]=[];for(let k=0;k<runs;k++){let eq=1,peak=1,dd=0;for(let i=0;i<ret.length;i++){eq*=1+ret[Math.floor(rnd()*ret.length)]/100;peak=Math.max(peak,eq);dd=Math.max(dd,(peak-eq)/peak*100)}finals.push((eq-1)*100);dds.push(dd)}finals.sort((a,b)=>a-b);dds.sort((a,b)=>a-b);return{simulations:runs,probabilityOfLoss:finals.filter(x=>x<0).length/runs*100,medianReturnPct:finals[Math.floor(runs*.5)]??0,p05ReturnPct:finals[Math.floor(runs*.05)]??0,p95MaxDrawdownPct:dds[Math.floor(runs*.95)]??0}}
function foldMinTrades(bars:number){return Math.max(12,Math.min(30,Math.floor(bars/150)))}
function aggregate(id:string,folds:StrategyResult[]):StrategyResult{return summarizeReturns(id,folds.flatMap(f=>f.tradeReturnsPct),10000)}
export async function runValidation(symbol='BTCUSDT',interval='1h',cfg:Partial<BacktestConfig>={},selectedStrategyId?:string):Promise<ValidationReport>{
 const config={...DEFAULT_BACKTEST_CONFIG,...cfg},candles=await fetchHistoricalCandles(symbol,interval,MAX_HISTORY_BARS);if(candles.length<MIN_HISTORY)throw new Error(`Need at least ${MIN_HISTORY.toLocaleString()} completed candles; received ${candles.length.toLocaleString()}.`);
 const ms=intervalMs(interval),gaps=candles.slice(1).filter((x,i)=>x.openTime-candles[i].openTime!==ms).length,dup=candles.length-new Set(candles.map(x=>x.openTime)).size,duration=(candles[candles.length-1].openTime-candles[0].openTime)/86400000,testStart=Math.floor(candles.length*PRE_OOS),pre=candles.slice(0,testStart),foldSize=Math.floor(pre.length/FOLDS),minFold=foldMinTrades(foldSize);
 const foldMap=new Map<string,StrategyResult[]>(),foldDiagnostics:Record<string,FoldDiagnostic[]>={};
 for(const st of STRATEGIES){const fs:StrategyResult[]=[],ds:FoldDiagnostic[]=[];for(let f=0;f<FOLDS;f++){const a=f*foldSize,b=f===FOLDS-1?pre.length:(f+1)*foldSize;if(b-a>=150){const result=simulate(candles,st.id,config,a,b);const d={fold:f+1,startBar:a,endBar:b,trades:result.trades,winRate:result.winRate,profitFactor:result.profitFactor,returnPct:result.returnPct,maxDrawdownPct:result.maxDrawdownPct,passesTrades:result.trades>=minFold,passesReturn:result.returnPct>0,passesProfitFactor:result.profitFactor>=MIN_PF,passesDrawdown:result.maxDrawdownPct<=MAX_DD,passed:result.trades>=minFold&&result.returnPct>0&&result.profitFactor>=MIN_PF&&result.maxDrawdownPct<=MAX_DD};fs.push(result);ds.push(d)}}foldMap.set(st.id,fs);foldDiagnostics[st.id]=ds}
 const candidates=STRATEGIES.map(s=>aggregate(s.id,foldMap.get(s.id)??[])).sort((a,b)=>b.score-a.score),qualified=STRATEGIES.map(s=>s.id).map(id=>({id,fs:foldMap.get(id)??[]})).filter(x=>x.fs.length===FOLDS&&x.fs.every(f=>f.trades>=minFold&&f.returnPct>0&&f.profitFactor>=MIN_PF&&f.maxDrawdownPct<=MAX_DD)),selectedId=selectedStrategyId&&qualified.some(x=>x.id===selectedStrategyId)?selectedStrategyId:qualified[0]?.id??null,selected=selectedId?STRATEGIES.find(s=>s.id===selectedId):null,validation=selected?aggregate(selected.id,foldMap.get(selected.id)??[]):null,test=selected?simulate(candles,selected.id,config,testStart,candles.length):null,monteCarlo=test?mc(test.tradeReturnsPct):mc([]),reasons:string[]=[];
 if(!selected){const best=candidates[0],bestFolds=best?foldDiagnostics[best.id]??[]:[],failed=bestFolds.filter(f=>!f.passed).map(f=>`fold ${f.fold}: PF ${f.profitFactor.toFixed(2)}, return ${f.returnPct.toFixed(2)}%, DD ${f.maxDrawdownPct.toFixed(2)}%, trades ${f.trades}`).join('; ');reasons.push(`No strategy passed all ${FOLDS} pre-OOS stability folds. Best candidate: ${best?.name??'none'} (aggregate PF ${best?.profitFactor.toFixed(2)??'0.00'}, ${best?.trades??0} trades). ${failed||'No fold diagnostics available.'} Minimum trades per fold is ${minFold}.`)}
 if(test){if(test.trades<MIN_TEST)reasons.push(`Out-of-sample test has only ${test.trades} trades; at least ${MIN_TEST} are required.`);if(test.profitFactor<MIN_PF)reasons.push(`Out-of-sample profit factor ${test.profitFactor.toFixed(2)} is below ${MIN_PF.toFixed(2)}.`);if(test.returnPct<=0)reasons.push(`Out-of-sample return ${test.returnPct.toFixed(2)}% is not positive.`);if(test.maxDrawdownPct>MAX_DD)reasons.push(`Out-of-sample max drawdown ${test.maxDrawdownPct.toFixed(2)}% exceeds ${MAX_DD.toFixed(0)}%.`);if(test.trades>=MIN_TEST&&test.profitFactor>=MIN_PF&&test.returnPct>0&&test.maxDrawdownPct<=MAX_DD&&monteCarlo.probabilityOfLoss>45)reasons.push(`Monte Carlo loss probability ${monteCarlo.probabilityOfLoss.toFixed(1)}% exceeds 45%.`)}
 const gate:ValidationGate={status:reasons.length?'REJECTED':'VALIDATED',reasons,minimumTestTrades:MIN_TEST,minimumProfitFactor:MIN_PF,minimumTestReturnPct:0,maximumTestDrawdownPct:MAX_DD,maximumMonteCarloLossProbability:45};
 return{symbol,interval,candles:candles.length,dataQuality:{startTime:candles[0].openTime,endTime:candles[candles.length-1].openTime,durationDays:duration,expectedIntervalMinutes:ms/60000,gaps,duplicateTimestamps:dup},costs:{feeBps:config.feeBps,slippageBps:config.slippageBps,roundTripPct:(2*config.feeBps+2*config.slippageBps)/10000},strategies:candidates,walkForward:{trainBars:foldSize,validationBars:foldSize,testBars:candles.length-testStart,selectedStrategy:selected?.name??'No eligible strategy',validation,test},foldDiagnostics,monteCarlo,gate,generatedAt:new Date().toISOString(),research:{asOf:new Date().toISOString(),dataWindowBars:candles.length,selectionMethod:`Three non-overlapping pre-OOS folds over the first ${Math.round(PRE_OOS*100)}% of history. Each candidate needs at least ${minFold} trades per fold, positive return, PF >= ${MIN_PF.toFixed(2)} and max drawdown <= ${MAX_DD}%. Final ${Math.round((1-PRE_OOS)*100)}% remains untouched OOS.`,coverage:['fees','slippage','adaptive volatility thresholds','regime/efficiency filters','volume confirmation','cost-aware sizing including round-trip costs','adaptive per-fold trade minimum','three non-overlapping folds','compound fold aggregation','fold-by-fold diagnostics','untouched OOS','Monte Carlo','no unqualified fallback']}};
}