import { PGlite } from '@electric-sql/pglite';
import { PGliteWorker } from '@electric-sql/pglite/worker';
import { TRADING_CONFIG } from './tradingConfig';
type DbClient = PGlite | PGliteWorker;let dbInstance:DbClient|null=null;let initPromise:Promise<DbClient>|null=null;
const SCHEMA_SQL=`
CREATE TABLE IF NOT EXISTS tp_account (id integer PRIMARY KEY DEFAULT 1,cash numeric(20,2) NOT NULL DEFAULT 10000.00,equity numeric(20,2) NOT NULL DEFAULT 10000.00,total_pnl numeric(20,2) NOT NULL DEFAULT 0.00,realized_pnl numeric(20,2) NOT NULL DEFAULT 0.00,bot_status text NOT NULL DEFAULT 'STOPPED',started_at timestamptz,last_tick_at timestamptz,max_positions integer NOT NULL DEFAULT 3,max_strategies integer NOT NULL DEFAULT 10,max_allocation_pct numeric(5,2) NOT NULL DEFAULT 20.00,default_allocation_pct numeric(5,2) NOT NULL DEFAULT 15.00,stop_loss_pct numeric(5,2) NOT NULL DEFAULT 2.00,take_profit_pct numeric(5,2) NOT NULL DEFAULT 4.00,confidence_threshold_pct numeric(5,2) NOT NULL DEFAULT 85.00,leverage numeric(5,2) NOT NULL DEFAULT 1.00,loss_limit_pct numeric(5,2) NOT NULL DEFAULT 2.00,risk_pause_until timestamptz,fee_bps numeric(6,2) NOT NULL DEFAULT 10.00,slippage_bps numeric(6,2) NOT NULL DEFAULT 2.00,risk_level text NOT NULL DEFAULT 'Balanced',theme text NOT NULL DEFAULT 'Dark',trade_alerts boolean NOT NULL DEFAULT true,pnl_alerts boolean NOT NULL DEFAULT true,risk_alerts boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tp_positions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),symbol text NOT NULL,side text NOT NULL,quantity numeric(20,8) NOT NULL,entry_price numeric(20,8) NOT NULL,current_price numeric(20,8) NOT NULL,notional numeric(20,2) NOT NULL,unrealized_pnl numeric(20,2) NOT NULL DEFAULT 0.00,stop_loss numeric(20,8) NOT NULL,take_profit numeric(20,8) NOT NULL,strategy text NOT NULL DEFAULT 'AI Signal',status text NOT NULL DEFAULT 'OPEN',opened_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tp_trades (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),symbol text NOT NULL,side text NOT NULL,quantity numeric(20,8) NOT NULL,entry_price numeric(20,8) NOT NULL,exit_price numeric(20,8) NOT NULL,pnl numeric(20,2) NOT NULL,return_pct numeric(10,2) NOT NULL,strategy text NOT NULL DEFAULT 'AI Signal',status text NOT NULL DEFAULT 'CLOSED',opened_at timestamptz NOT NULL,closed_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tp_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),equity numeric(20,2) NOT NULL,cash numeric(20,2) NOT NULL,open_value numeric(20,2) NOT NULL,unrealized_pnl numeric(20,2) NOT NULL,realized_pnl numeric(20,2) NOT NULL,ts timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tp_validation_gate (id integer PRIMARY KEY DEFAULT 1,status text NOT NULL DEFAULT 'REJECTED',symbol text NOT NULL DEFAULT 'BTCUSDT',interval text NOT NULL DEFAULT '5m',candles integer NOT NULL DEFAULT 0,test_return_pct numeric(12,4) NOT NULL DEFAULT 0,test_profit_factor numeric(12,4) NOT NULL DEFAULT 0,monte_carlo_loss_pct numeric(12,4) NOT NULL DEFAULT 100,strategy_version text NOT NULL DEFAULT 'v27',generated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_tp_snapshots_ts ON tp_snapshots(ts);CREATE INDEX IF NOT EXISTS idx_tp_trades_closed_at ON tp_trades(closed_at);`;
const SEED_SQL=`INSERT INTO tp_account(id,cash,equity,total_pnl,realized_pnl,bot_status) SELECT 1,10000.00,10000.00,0.00,0.00,'STOPPED' WHERE NOT EXISTS(SELECT 1 FROM tp_account WHERE id=1);INSERT INTO tp_validation_gate(id,status,strategy_version) VALUES(1,'REJECTED,'${TRADING_CONFIG.strategyVersion}') ON CONFLICT(id) DO NOTHING;`;
export async function getDb():Promise<DbClient>{if(dbInstance)return dbInstance;if(initPromise)return initPromise;initPromise=(async()=>{const browser=typeof window!=='undefined'&&typeof Worker!=='undefined'&&typeof indexedDB!=='undefined';const db=browser?await PGliteWorker.create(new Worker(new URL('./db-worker.ts',import.meta.url),{type:'module'}),{dataDir:'idb://tradepilot',id:'tradepilot-db'}):new PGlite();await db.exec(SCHEMA_SQL);for(const sql of [`ALTER TABLE tp_account ADD COLUMN IF NOT EXISTS max_strategies integer NOT NULL DEFAULT 10`,`ALTER TABLE tp_account ADD COLUMN IF NOT EXISTS loss_limit_pct numeric(5,2) NOT NULL DEFAULT 2.00`,`ALTER TABLE tp_account ADD COLUMN IF NOT EXISTS risk_pause_until timestamptz`,`ALTER TABLE tp_account ADD COLUMN IF NOT EXISTS fee_bps numeric(6,2) NOT NULL DEFAULT 10.00`,`ALTER TABLE tp_account ADD COLUMN IF NOT EXISTS slippage_bps numeric(6,2) NOT NULL DEFAULT 2.00`,`ALTER TABLE tp_account ADD COLUMN IF NOT EXISTS confidence_threshold_pct numeric(5,2) NOT NULL DEFAULT 85.00`,`ALTER TABLE tp_account ADD COLUMN IF NOT EXISTS leverage numeric(5,2) NOT NULL DEFAULT 1.00`,`ALTER TABLE tp_validation_gate ADD COLUMN IF NOT EXISTS strategy_version text NOT NULL DEFAULT 'v27'`])await db.exec(sql);await db.exec(`UPDATE tp_account SET max_strategies=LEAST(GREATEST(max_strategies,1),10),max_allocation_pct=LEAST(GREATEST(max_allocation_pct,1),20),leverage=LEAST(GREATEST(leverage,1),10),loss_limit_pct=LEAST(GREATEST(loss_limit_pct,.25),20),confidence_threshold_pct=LEAST(GREATEST(confidence_threshold_pct,85),95);`);await db.exec(SEED_SQL);await db.exec(`UPDATE tp_validation_gate SET status='REJECTED',strategy_version='${TRADING_CONFIG.strategyVersion}' WHERE strategy_version<>'${TRADING_CONFIG.strategyVersion}';`);dbInstance=db;return db;})();try{return await initPromise;}catch(e){initPromise=null;dbInstance=null;throw e;}}
export async function resetDatabase(){const db=await getDb();await db.exec('DELETE FROM tp_snapshots;');await db.exec('DELETE FROM tp_trades;');await db.exec('DELETE FROM tp_positions;');await db.exec(`UPDATE tp_account SET cash=10000,equity=10000,total_pnl=0,realized_pnl=0,bot_status='STOPPED',started_at=NULL,last_tick_at=NULL,risk_pause_until=NULL,max_strategies=10,max_allocation_pct=20,leverage=1,loss_limit_pct=2,fee_bps=10,slippage_bps=2,confidence_threshold_pct=85;`);await db.exec(`UPDATE tp_validation_gate SET status='REJECTED',symbol='BTCUSDT',interval='5m',candles=0,test_return_pct=0,test_profit_factor=0,monte_carlo_loss_pct=100,strategy_version='${TRADING_CONFIG.strategyVersion}',generated_at=now() WHERE id=1;`);}
export async function query<T=Record<string,unknown>>(sql:string,params?:unknown[]):Promise<T[]>{const db=await getDb();const r=await db.query(sql,params??[]);return(r.rows??[]) as T[];}
export async function execute(sql:string,params?:unknown[]){const db=await getDb();await db.query(sql,params??[]);}
export type ValidationGateRecord={status:'VALIDATED'|'REJECTED';symbol:string;interval:string;candles:number;test_return_pct:number;test_profit_factor:number;monte_carlo_loss_pct:number;strategy_version:string;generated_at:string};
export async function getValidationGate():Promise<ValidationGateRecord>{const rows=await query<ValidationGateRecord>(`SELECT status,symbol,interval,candles,test_return_pct,test_profit_factor,monte_carlo_loss_pct,strategy_version,generated_at FROM tp_validation_gate WHERE id=1;`);const g=rows[0];if(!g||g.strategy_version!==TRADING_CONFIG.strategyVersion)return{status:'REJECTED',symbol:'BTCUSDT',interval:'5m',candles:0,test_return_pct:0,test_profit_factor:0,monte_carlo_loss_pct:100,strategy_version:TRADING_CONFIG.strategyVersion,generated_at:new Date(0).toISOString()};return g;}
export async function setValidationGate(gate:{status:'VALIDATED'|'REJECTED';symbol:string;interval:string;candles:number;testReturnPct:number;testProfitFactor:number;monteCarloLossPct:number}):Promise<void>{await execute(`INSERT INTO tp_validation_gate(id,status,symbol,interval,candles,test_return_pct,test_profit_factor,monte_carlo_loss_pct,strategy_version,generated_at) VALUES(1,$1,$2,$3,$4,$5,$6,$7,$8,now()) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,symbol=EXCLUDED.symbol,interval=EXCLUDED.interval,candles=EXCLUDED.candles,test_return_pct=EXCLUDED.test_return_pct,test_profit_factor=EXCLUDED.test_profit_factor,monte_carlo_loss_pct=EXCLUDED.monte_carlo_loss_pct,strategy_version=EXCLUDED.strategy_version,generated_at=EXCLUDED.generated_at;`,[gate.status,gate.symbol,gate.interval,gate.candles,gate.testReturnPct,gate.testProfitFactor,gate.monteCarloLossPct,TRADING_CONFIG.strategyVersion]);}
