import { query, execute, resetDatabase, getValidationGate } from './db';
import { getAccount, getPositions, getTrades } from './repository';
import { fetchLatestBars, type MarketBar } from './marketData';
import { evaluateProductionStrategy, type StrategySignal } from './strategy';
import { TRADING_CONFIG } from './tradingConfig';
import { FINAL_TARGET_R, TARGET_LADDER, protectedStopAfterTarget } from './targetLadder';
import type { AiRecommendation, MarketTick, Position } from './types';

const SYMBOLS=['BTCUSDT','ETHUSDT','SOLUSDT','BNBUSDT'];
const POLL_MS=15000;
const LOCKOUT_MS=24*60*60*1000;
const intervalMs=(v:string)=>{const m=v.match(/^(\d+)([mhd])$/i);if(!m)throw new Error(`Unsupported interval: ${v}`);const n=Number(m[1]),u=m[2].toLowerCase();return n*(u==='m'?60000:u==='h'?3600000:86400000);};
const contextFor=(v:string)=>TRADING_CONFIG.lookback+TRADING_CONFIG.capacitySamples*(TRADING_CONFIG.maxBarsInTrade[v]??240)+300;
const key=(s:string,i:string)=>`${s}:${i}`;
const round=(v:number,d=2)=>Math.round(v*10**d)/10**d;
const decimals=(p:number)=>p>=100?2:p>=1?4:6;
const newSignalId=()=>globalThis.crypto?.randomUUID?.()??`sig-${Date.now()}-${Math.random().toString(36).slice(2)}`;
interface State{symbol:string;interval:string;bars:MarketBar[];updatedAt:number;}
interface Opportunity{symbol:string;interval:string;bar:MarketBar;signal:StrategySignal;quality:number;}
const states=new Map<string,State>();
let running=false,tickCount=0,timer:ReturnType<typeof setInterval>|null=null,snapshotTimer:ReturnType<typeof setInterval>|null=null,ticking=false,lastEntryAt=-Infinity,sessionStartEquity=TRADING_CONFIG.paperStartingCapital,peakEquity=TRADING_CONFIG.paperStartingCapital,day='',activeSymbol='BTCUSDT',activeInterval='5m',activeValidationStatus='REJECTED';

const pnl=(side:'LONG'|'SHORT',entry:number,price:number,qty:number)=>round((side==='LONG'?1:-1)*(price-entry)*qty,2);
const dayKey=()=>new Date().toISOString().slice(0,10);
const merge=(a:MarketBar[],b:MarketBar[],limit:number)=>{const m=new Map<number,MarketBar>();for(const x of [...a,...b])m.set(x.openTime,x);return [...m.values()].sort((x,y)=>x.openTime-y.openTime).slice(-limit);};

async function resolvePaperConfig(){const gate=await getValidationGate();activeSymbol=SYMBOLS.includes(gate.symbol)?gate.symbol:'BTCUSDT';activeInterval=TRADING_CONFIG.timeframes.includes(gate.interval as typeof TRADING_CONFIG.timeframes[number])?gate.interval:'5m';activeValidationStatus=gate.status;return gate;}
async function loadAll(){await resolvePaperConfig();states.clear();try{const bars=await fetchLatestBars(activeSymbol,activeInterval,Math.min(50000,contextFor(activeInterval)));states.set(key(activeSymbol,activeInterval),{symbol:activeSymbol,interval:activeInterval,bars,updatedAt:Date.now()});}catch(e){throw new Error(`No completed Binance market data for validated paper configuration ${activeSymbol} ${activeInterval}: ${e instanceof Error?e.message:String(e)}`);}if(!states.size)throw new Error('No completed Binance market data is available; synthetic prices are disabled.');}
async function refresh(){const now=Date.now();for(const s of states.values()){const last=s.bars.at(-1);if(!last||now-last.openTime<intervalMs(s.interval))continue;try{s.bars=merge(s.bars,await fetchLatestBars(s.symbol,s.interval,1000),Math.min(50000,contextFor(s.interval)));s.updatedAt=now;}catch(e){console.warn(`[paper] refresh skipped ${s.symbol} ${s.interval}`,e);}}}
async function daily(){const k=dayKey();if(k!==day){day=k;sessionStartEquity=(await getAccount()).equity;}}
function profile(a:Awaited<ReturnType<typeof getAccount>>){const base=Math.max(TRADING_CONFIG.minScore,Math.min(95,Math.round(a.confidence_threshold_pct||TRADING_CONFIG.minScore)));if(a.risk_level==='Conservative')return{minScore:Math.max(92,base),risk:.15,allocation:15};if(a.risk_level==='Aggressive')return{minScore:base,risk:.35,allocation:20};return{minScore:base,risk:TRADING_CONFIG.riskPerTradePct,allocation:TRADING_CONFIG.maxAllocationPct};}
async function losses(){let n=0;for(const t of await getTrades(100)){if(t.pnl<0)n++;else break;}return n;}
async function scan(a:Awaited<ReturnType<typeof getAccount>>,held:Set<string>){const p=profile(a),out:Opportunity[]=[];for(const s of states.values()){if(s.symbol!==activeSymbol||s.interval!==activeInterval||held.has(s.symbol))continue;const bar=s.bars.at(-1);if(!bar)continue;const signal=evaluateProductionStrategy(s.bars,{minScore:p.minScore,lookback:TRADING_CONFIG.lookback,feeBps:a.fee_bps,slippageBps:a.slippage_bps,minStopAtr:TRADING_CONFIG.minStopAtr,maxStructuralRiskAtr:TRADING_CONFIG.maxStructuralRiskAtr,maxCostFractionOfRisk:TRADING_CONFIG.maxCostFractionOfRisk,swingLookback:TRADING_CONFIG.swingLookback,capacityHorizonBars:TRADING_CONFIG.maxBarsInTrade[s.interval]??240,capacityBars:s.bars} as any);if(signal.action==='WAIT'||signal.score<p.minScore)continue;const risk=Math.abs(signal.entry-signal.stopLoss);if(!(risk>0))continue;const costR=signal.entry*2*(a.fee_bps+a.slippage_bps)/10000/risk;out.push({symbol:s.symbol,interval:s.interval,bar,signal,quality:signal.score*Math.max(0,1-costR)});}return out.sort((a,b)=>b.quality-a.quality);}

async function realize(id:string,qty:number,raw:number,reason:string){const rows=await query<Record<string,unknown>>(`SELECT * FROM tp_positions WHERE id=$1 AND status='OPEN';`,[id]);if(!rows.length)return false;const r=rows[0],side=r.side as 'LONG'|'SHORT',oldQty=Number(r.quantity),entry=Number(r.entry_price),notional=Number(r.notional),a=await getAccount(),q=Math.min(Math.max(qty,0),oldQty);if(!(q>0))return false;const slip=a.slippage_bps/10000,exit=round(raw*(1-(side==='LONG'?slip:-slip)),decimals(entry)),gross=(side==='LONG'?1:-1)*(exit-entry)*q,fees=(entry*q+exit*q)*a.fee_bps/10000,net=round(gross-fees,2),fraction=q/oldQty,margin=notional/Math.max(1,a.leverage)*fraction,remain=oldQty-q;
 await execute(`INSERT INTO tp_trades (symbol,side,quantity,entry_price,exit_price,pnl,return_pct,strategy,signal_id,timeframe,strategy_version,signal_timestamp,signal_entry,signal_stop_loss,final_take_profit,gross_pnl,fees,exit_reason,status,opened_at,closed_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,'CLOSED',$19,now());`,[String(r.symbol),side,q,entry,exit,net,round(margin?net/margin*100:0,2),String(r.strategy??'Strategy'),r.signal_id==null?null:String(r.signal_id),String(r.timeframe??activeInterval),r.strategy_version==null?TRADING_CONFIG.strategyVersion:String(r.strategy_version),r.signal_timestamp==null?null:String(r.signal_timestamp),r.signal_entry==null?null:Number(r.signal_entry),r.signal_stop_loss==null?null:Number(r.signal_stop_loss),r.final_take_profit==null?null:Number(r.final_take_profit),round(gross,2),round(fees,8),reason,String(r.opened_at)]);
 if(remain<=Math.max(1e-10,oldQty*1e-8))await execute(`DELETE FROM tp_positions WHERE id=$1;`,[id]);else await execute(`UPDATE tp_positions SET quantity=$1,notional=$2,unrealized_pnl=0 WHERE id=$3;`,[remain,remain*entry,id]);
 await execute(`UPDATE tp_account SET cash=cash+$1,realized_pnl=realized_pnl+$2 WHERE id=1;`,[margin+net,net]);return true;}

async function closePositionInternal(id:string,raw?:number,reason='Manual'){const rows=await query<Record<string,unknown>>(`SELECT * FROM tp_positions WHERE id=$1 AND status='OPEN';`,[id]);if(!rows.length)return false;const r=rows[0],symbol=String(r.symbol),tf=String(r.timeframe??activeInterval),state=states.get(key(symbol,tf));return realize(id,Number(r.quantity),raw??state?.bars.at(-1)?.close??Number(r.current_price),reason);}
async function equity(){const a=await getAccount(),ps=await getPositions(),margin=ps.reduce((x,p)=>x+p.notional/Math.max(1,a.leverage),0),u=ps.reduce((x,p)=>x+p.unrealized_pnl,0),eq=round(a.cash+margin+u,2);peakEquity=Math.max(peakEquity,eq);await execute(`UPDATE tp_account SET equity=$1,total_pnl=$2 WHERE id=1;`,[eq,round(a.realized_pnl+u,2)]);}
async function riskPause(reason:string){for(const p of await getPositions())await closePositionInternal(p.id,undefined,`CAPITAL PROTECTION: ${reason}`);const until=new Date(Date.now()+LOCKOUT_MS).toISOString();running=false;if(timer)clearInterval(timer);if(snapshotTimer)clearInterval(snapshotTimer);timer=null;snapshotTimer=null;await execute(`UPDATE tp_account SET bot_status='STOPPED',risk_pause_until=$1,last_tick_at=now() WHERE id=1;`,[until]);}

async function tick(){if(!running||ticking)return;ticking=true;try{await daily();await refresh();const closed=new Set<string>();const rows=await query<Record<string,unknown>>(`SELECT * FROM tp_positions WHERE status='OPEN';`);
 for(const r of rows){const id=String(r.id),symbol=String(r.symbol),sideText=r.side as 'LONG'|'SHORT',side=sideText==='LONG'?1:-1,entry=Number(r.entry_price),oldQty=Number(r.quantity),risk=Number(r.initial_risk)||Math.abs(entry-Number(r.stop_loss)),stage=Number(r.target_stage)||0,tf=String(r.timeframe??activeInterval),state=states.get(key(symbol,tf));const bar=state?.bars.at(-1);if(!bar)continue;const price=round(bar.close,decimals(entry));await execute(`UPDATE tp_positions SET current_price=$1,unrealized_pnl=$2 WHERE id=$3;`,[price,pnl(sideText,entry,price,oldQty),id]);
  const stop=Number(r.stop_loss),stopHit=side===1?bar.low<=stop:bar.high>=stop;if(stopHit){await closePositionInternal(id,stop,'Stop Loss');closed.add(symbol);continue;}
  let current=stage,remaining=oldQty;
  for(let i=current;i<TARGET_LADDER.length;i++){const level=TARGET_LADDER[i],target=entry+side*risk*level.r,hit=side===1?bar.high>=target:bar.low<=target;if(!hit)break;const usedBefore=TARGET_LADDER.slice(0,i).reduce((s,x)=>s+x.fraction,0),remainingFraction=Math.max(1e-9,1-usedBefore),qty=i===TARGET_LADDER.length-1?remaining:remaining*level.fraction/remainingFraction;if(!await realize(id,qty,target,`TP${i+1} ${level.r}R`))break;current=i+1;remaining-=qty;if(i===TARGET_LADDER.length-1){closed.add(symbol);break;}const newStop=protectedStopAfterTarget(side,entry,risk,current,stop),next=entry+side*risk*TARGET_LADDER[current].r;await execute(`UPDATE tp_positions SET target_stage=$1,stop_loss=$2,take_profit=$3 WHERE id=$4;`,[current,round(newStop,decimals(entry)),round(next,decimals(entry)),id]);}
 }
 await equity();const a=await getAccount(),dd=peakEquity>0?(peakEquity-a.equity)/peakEquity*100:0,dailyDd=sessionStartEquity>0?(sessionStartEquity-a.equity)/sessionStartEquity*100:0;if(dailyDd>=Math.min(a.loss_limit_pct,TRADING_CONFIG.maxDailyLossPct)){await riskPause(`daily loss limit ${Math.min(a.loss_limit_pct,TRADING_CONFIG.maxDailyLossPct).toFixed(2)}% reached`);return;}if(dd>=TRADING_CONFIG.maxAccountDrawdownPct){await riskPause(`account drawdown ${dd.toFixed(2)}% reached`);return;}if(await losses()>=TRADING_CONFIG.maxConsecutiveLosses){await riskPause(`${TRADING_CONFIG.maxConsecutiveLosses} consecutive losses reached`);return;}
 const ps=await getPositions();const cooldownMs=TRADING_CONFIG.cooldownBars*intervalMs(activeInterval);if(ps.length<Math.min(a.max_positions,TRADING_CONFIG.maxPositions)&&Date.now()-lastEntryAt>=cooldownMs)await openBest(a,ps,closed);await equity();await execute(`UPDATE tp_account SET last_tick_at=now() WHERE id=1;`);tickCount++;
 }catch(e){console.error('[paper] tick error',e);}finally{ticking=false;}}

async function openBest(a:Awaited<ReturnType<typeof getAccount>>,positions:Position[],closed:Set<string>){const held=new Set([...positions.map(p=>p.symbol),...closed]),best=(await scan(a,held))[0];if(!best)return;const {symbol,interval,bar,signal}=best,side=signal.action==='LONG'?1:-1,signalId=newSignalId(),signalRisk=Math.abs(signal.entry-signal.stopLoss),entry=round(bar.close*(1+side*a.slippage_bps/10000),decimals(bar.close)),risk=signalRisk,cost=2*(a.fee_bps+a.slippage_bps)/10000,p=profile(a),budget=a.equity*p.risk/100,maxNotional=a.equity*Math.min(a.max_allocation_pct,p.allocation,TRADING_CONFIG.maxAllocationPct)/100,q=Math.min(budget/Math.max(risk+entry*cost,entry*1e-9),maxNotional/entry),notional=q*entry,leverage=Math.min(Math.max(1,a.leverage),TRADING_CONFIG.maxLeverage),margin=notional/leverage;if(!Number.isFinite(q)||q<=0||notional<TRADING_CONFIG.minNotionalUsd||margin>a.cash||!(risk>0))return;const stop=round(entry-side*risk,decimals(entry)),first=round(entry+side*risk*TARGET_LADDER[0].r,decimals(entry)),finalTarget=round(entry+side*risk*FINAL_TARGET_R,decimals(entry));await execute(`INSERT INTO tp_positions (symbol,side,quantity,entry_price,current_price,notional,unrealized_pnl,stop_loss,take_profit,initial_risk,target_stage,timeframe,strategy,signal_id,strategy_version,signal_timestamp,signal_entry,signal_stop_loss,final_take_profit,status) VALUES ($1,$2,$3,$4,$4,$5,0,$6,$7,$8,0,$9,$10,$11,$12,$13,$14,$15,$16,'OPEN');`,[symbol,signal.action,q,entry,notional,stop,first,risk,interval,`${signal.strategy} | fixed 1:2 ladder`,signalId,TRADING_CONFIG.strategyVersion,new Date(bar.openTime).toISOString(),signal.entry,signal.stopLoss,finalTarget]);await execute(`UPDATE tp_account SET cash=cash-$1 WHERE id=1;`,[margin]);lastEntryAt=Date.now();}

export function getTickCount(){return tickCount;}
export function isEngineRunning(){return running;}
export function getActivePaperConfig(){return{symbol:activeSymbol,interval:activeInterval,strategyVersion:TRADING_CONFIG.strategyVersion,finalTargetR:FINAL_TARGET_R,validationStatus:activeValidationStatus};}
export function getMarketTicks():MarketTick[]{const out:MarketTick[]=[];for(const symbol of SYMBOLS){const s=states.get(key(symbol,activeInterval));const a=s?.bars.at(-1),b=s?.bars.at(-2);if(a)out.push({symbol:symbol.replace('USDT','/USDT'),price:round(a.close,decimals(a.close)),change_pct:b?round((a.close-b.close)/b.close*100,2):0,ts:a.openTime});}return out;}
export function getPriceHistory(symbol:string,points=TRADING_CONFIG.lookback){const k=symbol.replace('/','').toUpperCase(),s=states.get(key(k,activeInterval));return s?s.bars.slice(-points).map(b=>({ts:b.openTime,price:b.close})):[];}
export async function startEngine(){if(running)return{ok:false,message:'Engine is already running.'};const a=await getAccount();if(a.bot_status==='RUNNING')return{ok:false,message:'Bot is already RUNNING.'};if(a.risk_pause_until&&new Date(a.risk_pause_until).getTime()>Date.now())return{ok:false,message:`Risk lockout active until ${new Date(a.risk_pause_until).toLocaleString()}.`};const gate=await loadAll();const rows=await query<{peak:number}>(`SELECT COALESCE(MAX(equity),0) AS peak FROM tp_snapshots;`);peakEquity=Math.max(TRADING_CONFIG.paperStartingCapital,Number(rows[0]?.peak)||0,a.equity);await daily();sessionStartEquity=a.equity;lastEntryAt=-Infinity;running=true;await execute(`UPDATE tp_account SET bot_status='RUNNING',started_at=now(),last_tick_at=now() WHERE id=1;`);timer=setInterval(()=>void tick(),POLL_MS);snapshotTimer=setInterval(()=>void snapshot(),15000);void tick();const mode=gate.status==='VALIDATED'?'VALIDATED':'RESEARCH';return{ok:true,message:`Paper engine started in ${mode} mode on ${activeSymbol} ${activeInterval}. Strategy ${TRADING_CONFIG.strategyVersion}; fixed ${FINAL_TARGET_R}R final target with 1R / 1.5R / 2R partial exits. Historical validation: ${gate.status}.`};}
export async function stopEngine(){running=false;if(timer)clearInterval(timer);if(snapshotTimer)clearInterval(snapshotTimer);timer=null;snapshotTimer=null;await execute(`UPDATE tp_account SET bot_status='STOPPED',last_tick_at=now() WHERE id=1;`);return{ok:true,message:'Paper bot stopped.'};}
export async function restartEngine(){await stopEngine();await new Promise(r=>setTimeout(r,250));return startEngine();}
export async function closePosition(id:string,exitPrice?:number,reason?:string){const ok=await closePositionInternal(id,exitPrice,reason??'Manual');return ok?{ok:true,message:`Position closed (${reason??'Manual'}).`}:{ok:false,message:'Position not found or already closed.'};}
async function snapshot(){if(!running)return;try{const a=await getAccount(),ps=await getPositions();await execute(`INSERT INTO tp_snapshots (equity,cash,open_value,unrealized_pnl,realized_pnl,ts) VALUES ($1,$2,$3,$4,$5,now());`,[a.equity,a.cash,ps.reduce((x,p)=>x+p.notional,0),ps.reduce((x,p)=>x+p.unrealized_pnl,0),a.realized_pnl]);}catch(e){console.error('[paper] snapshot error',e);}}
export async function closeAllPositions(){const ps=await getPositions();for(const p of ps)await closePositionInternal(p.id,undefined,'Close All');return{ok:true,message:`Closed ${ps.length} positions.`};}
export async function resetAccount(){if(running)await stopEngine();await resetDatabase();states.clear();tickCount=0;lastEntryAt=-Infinity;day=dayKey();sessionStartEquity=TRADING_CONFIG.paperStartingCapital;peakEquity=TRADING_CONFIG.paperStartingCapital;activeSymbol='BTCUSDT';activeInterval='5m';activeValidationStatus='REJECTED';return{ok:true,message:`Account reset to $${TRADING_CONFIG.paperStartingCapital}.`};}
export async function getAiRecommendation(symbol?:string):Promise<AiRecommendation>{if(!states.size)await loadAll();const k=(symbol??activeSymbol).replace('/','').toUpperCase();if(k!==activeSymbol)return{symbol:k.replace('USDT','/USDT'),action:'WAIT',confidence:0,threshold:Math.max(TRADING_CONFIG.minScore,(await getAccount()).confidence_threshold_pct),entry:0,stop_loss:0,take_profit:0,risk_score:100,explanation:`Paper engine is locked to the validated configuration ${activeSymbol} ${activeInterval}.`};const a=await getAccount(),best=(await scan(a,new Set())).find(x=>x.symbol===k);if(!best)return{symbol:k.replace('USDT','/USDT'),action:'WAIT',confidence:0,threshold:Math.max(TRADING_CONFIG.minScore,a.confidence_threshold_pct),entry:0,stop_loss:0,take_profit:0,risk_score:100,explanation:`No statistically qualified opportunity on the validated ${activeInterval} configuration.`};const side=best.signal.action==='LONG'?1:-1,risk=Math.abs(best.signal.entry-best.signal.stopLoss);return{symbol:k.replace('USDT','/USDT'),action:best.signal.action==='LONG'?'LONG':'SHORT',confidence:best.signal.confidence,threshold:Math.max(TRADING_CONFIG.minScore,a.confidence_threshold_pct),entry:best.signal.entry,stop_loss:best.signal.stopLoss,take_profit:best.signal.entry+side*risk*FINAL_TARGET_R,risk_score:100-best.signal.confidence,targets:TARGET_LADDER.map(x=>({r:x.r,fraction:x.fraction,price:best.signal.entry+side*risk*x.r})),explanation:`${best.interval} ${best.signal.strategy}: fixed 1:${FINAL_TARGET_R} final target; progressive exits at ${TARGET_LADDER.map(x=>`${x.r}R`).join(', ')}. Execution is recorded separately from the signal.`};}
