import { query, execute, resetDatabase } from './db';
import { getAccount, getPositions } from './repository';
import { fetchLatestBars, type MarketBar } from './marketData';
import { evaluateProductionStrategy, type StrategySignal } from './strategy';
import { TRADING_CONFIG } from './tradingConfig';
import type { AiRecommendation, MarketTick, Position } from './types';

// PAPER TRADING ONLY. Real Binance public market data; no exchange orders and no synthetic prices.
const SYMBOLS=['BTCUSDT','ETHUSDT','SOLUSDT','BNBUSDT'];
const INTERVAL='5m';
const POLL_MS=5000;
const LOCKOUT_MS=24*60*60*1000;
interface MarketState{symbol:string;bars:MarketBar[];updatedAt:number;}
const states=new Map<string,MarketState>();
let tickCount=0,engineRunning=false,tickTimer:ReturnType<typeof setInterval>|null=null,snapshotTimer:ReturnType<typeof setInterval>|null=null,ticking=false,lastEntryTick=-Infinity,sessionStartEquity=10000,tradeDayKey='';
const round=(v:number,dp=2)=>{const f=10**dp;return Math.round(v*f)/f;};
const decimals=(p:number)=>p>=100?2:p>=1?4:6;
const dayKey=()=>new Date().toISOString().slice(0,10);
async function loadAll(){for(const symbol of SYMBOLS){try{const bars=await fetchLatestBars(symbol,INTERVAL,TRADING_CONFIG.lookback);states.set(symbol,{symbol,bars,updatedAt:Date.now()});}catch(err){console.warn(`[paper] no live data for ${symbol}`,err);}}if(!states.size)throw new Error('No live Binance market data is available; synthetic prices are disabled.');}
async function refresh(symbol:string){const bars=await fetchLatestBars(symbol,INTERVAL,TRADING_CONFIG.lookback);states.set(symbol,{symbol,bars,updatedAt:Date.now()});}
async function daily(){const key=dayKey();if(key!==tradeDayKey){tradeDayKey=key;sessionStartEquity=(await getAccount()).equity;}}
export function getTickCount(){return tickCount;}
export function isEngineRunning(){return engineRunning;}
export function getMarketTicks():MarketTick[]{return Array.from(states.values()).map(s=>{const a=s.bars.at(-1),b=s.bars.at(-2);return a?{symbol:s.symbol.replace('USDT','/USDT'),price:round(a.close,decimals(a.close)),change_pct:b?round((a.close-b.close)/b.close*100,2):0,ts:a.openTime}:null;}).filter(Boolean) as MarketTick[];}
export function getPriceHistory(symbol:string,points=TRADING_CONFIG.lookback){const key=symbol.replace('/','').toUpperCase(),s=states.get(key);return s?s.bars.slice(-points).map(b=>({ts:b.openTime,price:b.close})):[];}
export async function startEngine(){if(engineRunning)return{ok:false,message:'Engine is already running.'};const account=await getAccount();if(account.bot_status==='RUNNING')return{ok:false,message:'Bot is already RUNNING.'};if(account.risk_pause_until&&new Date(account.risk_pause_until).getTime()>Date.now())return{ok:false,message:`Risk lockout active until ${new Date(account.risk_pause_until).toLocaleString()}.`};await loadAll();await daily();sessionStartEquity=account.equity;engineRunning=true;await execute(`UPDATE tp_account SET bot_status='RUNNING',started_at=now(),last_tick_at=now() WHERE id=1;`);tickTimer=setInterval(()=>void tick(),POLL_MS);snapshotTimer=setInterval(()=>void snapshot(),15000);void tick();return{ok:true,message:'Paper engine started using real Binance market data and the same v28 strategy/risk model used by validation.'};}
export async function stopEngine(){engineRunning=false;if(tickTimer)clearInterval(tickTimer);if(snapshotTimer)clearInterval(snapshotTimer);tickTimer=null;snapshotTimer=null;await execute(`UPDATE tp_account SET bot_status='STOPPED',last_tick_at=now() WHERE id=1;`);return{ok:true,message:'Paper bot stopped.'};}
export async function restartEngine(){await stopEngine();await new Promise(r=>setTimeout(r,250));return startEngine();}
function pnl(p:Position,price:number){return round((p.side==='LONG'?1:-1)*(price-p.entry_price)*p.quantity,2);}
async function equity(){const a=await getAccount(),ps=await getPositions(),margin=ps.reduce((x,p)=>x+p.notional/Math.max(1,a.leverage),0),u=ps.reduce((x,p)=>x+p.unrealized_pnl,0);await execute(`UPDATE tp_account SET equity=$1,total_pnl=$2 WHERE id=1;`,[round(a.cash+margin+u,2),round(a.realized_pnl+u,2)]);}
async function riskPause(reason:string){for(const p of await getPositions())await closePosition(p.id,undefined,`CAPITAL PROTECTION: ${reason}`);const until=new Date(Date.now()+LOCKOUT_MS).toISOString();engineRunning=false;if(tickTimer)clearInterval(tickTimer);if(snapshotTimer)clearInterval(snapshotTimer);tickTimer=null;snapshotTimer=null;await execute(`UPDATE tp_account SET bot_status='STOPPED',risk_pause_until=$1,last_tick_at=now() WHERE id=1;`,[until]);}
function profile(a:Awaited<ReturnType<typeof getAccount>>){const base=Math.max(TRADING_CONFIG.minScore,Math.min(95,Math.round(a.confidence_threshold_pct||TRADING_CONFIG.minScore)));if(a.risk_level==='Conservative')return{minScore:Math.max(92,base),risk:.15,allocation:15};if(a.risk_level==='Aggressive')return{minScore:base,risk:.35,allocation:20};return{minScore:base,risk:TRADING_CONFIG.riskPerTradePct,allocation:TRADING_CONFIG.maxAllocationPct};}
async function tick(){if(!engineRunning||ticking)return;ticking=true;try{await daily();for(const s of SYMBOLS){try{await refresh(s);}catch(err){console.warn(`[paper] skipped ${s}; live data unavailable`,err);}}const closed=new Set<string>();for(const p of await getPositions()){const bar=states.get(p.symbol)?.bars.at(-1);if(!bar)continue;const price=round(bar.close,decimals(bar.close));await execute(`UPDATE tp_positions SET current_price=$1,unrealized_pnl=$2 WHERE id=$3;`,[price,pnl(p,price),p.id]);const stop=p.side==='LONG'?bar.low<=p.stop_loss:bar.high>=p.stop_loss,target=p.side==='LONG'?bar.high>=p.take_profit:bar.low<=p.take_profit;if(stop||target){closed.add(p.symbol);await closePosition(p.id,stop?p.stop_loss:p.take_profit,stop?'Stop Loss':'Take Profit');}}await equity();const a=await getAccount(),dd=sessionStartEquity>0?Math.max(0,(sessionStartEquity-a.equity)/sessionStartEquity*100):0;if(dd>=a.loss_limit_pct){await riskPause(`daily loss limit ${a.loss_limit_pct.toFixed(2)}% reached`);return;}const ps=await getPositions();if(ps.length<Math.min(a.max_positions,TRADING_CONFIG.maxPositions)&&tickCount-lastEntryTick>=TRADING_CONFIG.cooldownBars)await openBest(a,ps,closed);await equity();await execute(`UPDATE tp_account SET last_tick_at=now() WHERE id=1;`);tickCount++;}catch(err){console.error('[paper] tick error',err);}finally{ticking=false;}}
async function openBest(a:Awaited<ReturnType<typeof getAccount>>,positions:Position[],closed:Set<string>){const p=profile(a),held=new Set([...positions.map(x=>x.symbol),...closed]);let best:{symbol:string;bar:MarketBar;signal:StrategySignal}|null=null;for(const [symbol,state] of states){if(held.has(symbol))continue;const bar=state.bars.at(-1);if(!bar)continue;const signal=evaluateProductionStrategy(state.bars,{minScore:p.minScore,lookback:TRADING_CONFIG.lookback,feeBps:a.fee_bps,slippageBps:a.slippage_bps,maxStructuralRiskAtr:TRADING_CONFIG.maxStructuralRiskAtr,swingLookback:TRADING_CONFIG.swingLookback});if(signal.action==='WAIT'||signal.score<p.minScore)continue;const side=signal.action==='LONG'?1:-1,signalRisk=Math.abs(signal.entry-signal.stopLoss),entryGap=Math.abs(bar.open-signal.entry)/Math.max(signalRisk,bar.open*1e-6);if(!Number.isFinite(signalRisk)||signalRisk<=0||entryGap>.35)continue;if(!best||signal.score>best.signal.score)best={symbol,bar,signal};}if(!best)return;const {symbol,bar,signal}=best,side=signal.action==='LONG'?1:-1,slip=a.slippage_bps/10000,entry=round(bar.close*(1+side*slip),decimals(bar.close)),risk=Math.abs(entry-signal.stopLoss),riskBudget=a.equity*p.risk/100,maxNotional=a.equity*Math.min(a.max_allocation_pct,p.allocation,TRADING_CONFIG.maxAllocationPct)/100,q=Math.min(riskBudget/Math.max(risk,entry*.0008),maxNotional/entry),targetNotional=round(q*entry,2),margin=targetNotional/Math.max(1,a.leverage);if(!Number.isFinite(q)||q<=0||margin>a.cash)return;const stop=round(side===1?entry-risk:entry+risk,decimals(entry)),target=round(side===1?entry+risk*signal.riskReward:entry-risk*signal.riskReward,decimals(entry));await execute(`INSERT INTO tp_positions (symbol,side,quantity,entry_price,current_price,notional,unrealized_pnl,stop_loss,take_profit,strategy,status) VALUES ($1,$2,$3,$4,$4,$5,0,$6,$7,$8,'OPEN');`,[symbol,signal.action,q,entry,targetNotional,stop,target,`${signal.strategy} ${signal.riskReward.toFixed(1)}R`]);await execute(`UPDATE tp_account SET cash=cash-$1 WHERE id=1;`,[margin]);lastEntryTick=tickCount;}
export async function closePosition(id:string,exitPrice?:number,reason?:string){const rows=await query<Record<string,unknown>>(`SELECT * FROM tp_positions WHERE id=$1 AND status='OPEN';`,[id]);if(!rows.length)return{ok:false,message:'Position not found or already closed.'};const r=rows[0],p={id:String(r.id),symbol:String(r.symbol),side:r.side as 'LONG'|'SHORT',quantity:Number(r.quantity),entry_price:Number(r.entry_price),current_price:Number(r.current_price),notional:Number(r.notional),unrealized_pnl:Number(r.unrealized_pnl),stop_loss:Number(r.stop_loss),take_profit:Number(r.take_profit),strategy:String(r.strategy??'Strategy'),opened_at:String(r.opened_at)},a=await getAccount(),bar=states.get(p.symbol)?.bars.at(-1),raw=exitPrice??bar?.close??p.current_price,slip=a.slippage_bps/10000,exit=round(raw*(1-(p.side==='LONG'?slip:-slip)),decimals(p.entry_price)),dir=p.side==='LONG'?1:-1,gross=dir*(exit-p.entry_price)*p.quantity,fees=(p.entry_price*p.quantity+exit*p.quantity)*(a.fee_bps/10000),net=round(gross-fees,2),margin=p.notional/Math.max(1,a.leverage);await execute(`INSERT INTO tp_trades (symbol,side,quantity,entry_price,exit_price,pnl,return_pct,strategy,status,opened_at,closed_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,'CLOSED',$9,now());`,[p.symbol,p.side,p.quantity,p.entry_price,exit,net,round(margin?net/margin*100:0,2),p.strategy,p.opened_at]);await execute(`DELETE FROM tp_positions WHERE id=$1;`,[p.id]);await execute(`UPDATE tp_account SET cash=cash+$1,realized_pnl=realized_pnl+$2 WHERE id=1;`,[margin+net,net]);await equity();return{ok:true,message:`Position closed (${reason??'Manual'}). Net PnL after costs: ${net.toFixed(2)}`};}
async function snapshot(){if(!engineRunning)return;try{const a=await getAccount(),ps=await getPositions();await execute(`INSERT INTO tp_snapshots (equity,cash,open_value,unrealized_pnl,realized_pnl,ts) VALUES ($1,$2,$3,$4,$5,now());`,[a.equity,a.cash,ps.reduce((x,p)=>x+p.notional,0),ps.reduce((x,p)=>x+p.unrealized_pnl,0),a.realized_pnl]);}catch(err){console.error('[paper] snapshot error',err);}}
export async function closeAllPositions(){const ps=await getPositions();for(const p of ps)await closePosition(p.id,undefined,'Close All');return{ok:true,message:`Closed ${ps.length} positions.`};}
export async function resetAccount(){if(engineRunning)await stopEngine();await resetDatabase();states.clear();tickCount=0;lastEntryTick=-Infinity;tradeDayKey=dayKey();sessionStartEquity=10000;return{ok:true,message:'Account reset to $10,000.'};}
export async function getAiRecommendation(symbol?:string):Promise<AiRecommendation>{const key=(symbol??'BTCUSDT').replace('/','').toUpperCase();let state=states.get(key);if(!state){try{const bars=await fetchLatestBars(key,INTERVAL,TRADING_CONFIG.lookback);state={symbol:key,bars,updatedAt:Date.now()};states.set(key,state);}catch{return{symbol:key.replace('USDT','/USDT'),action:'WAIT',confidence:0,threshold:TRADING_CONFIG.minScore,entry:0,stop_loss:0,take_profit:0,risk_score:100,explanation:'Live Binance market data unavailable; synthetic fallback is disabled.'};}}const a=await getAccount(),signal=evaluateProductionStrategy(state.bars,{minScore:Math.max(TRADING_CONFIG.minScore,a.confidence_threshold_pct),feeBps:a.fee_bps,slippageBps:a.slippage_bps});return{symbol:key.replace('USDT','/USDT'),action:signal.action==='LONG'?'LONG':signal.action==='SHORT'?'SHORT':'WAIT',confidence:signal.confidence,threshold:Math.max(TRADING_CONFIG.minScore,a.confidence_threshold_pct),entry:signal.entry,stop_loss:signal.stopLoss,take_profit:signal.takeProfit,risk_score:100-signal.confidence,explanation:signal.reasons.join('. ')};}
