export type TradingMode = 'PAPER';

/** v39 selective BTCUSDT trend-pullback configuration. Fixed 1:2 R:R. */
export const TRADING_CONFIG = {
  mode: 'PAPER' as TradingMode,
  strategyVersion: 'v39',
  minScore: 80,
  ultraScore: 90,
  researchMinRiskReward: 2,
  researchMaxRiskReward: 2,
  productionMinRiskReward: 2,
  productionMaxRiskReward: 2,
  atrStopMultiple: 1.5,
  minStopAtr: 0.80,
  maxStructuralRiskAtr: 2.5,
  maxCostFractionOfRisk: 0.50,
  swingLookback: 5,
  lookback: 400,
  paperStartingCapital: 50 as number,
  riskPerTradePct: 0.5,
  maxAllocationPct: 20,
  maxPositions: 1,
  cooldownBars: 12,
  feeBps: 10,
  slippageBps: 2,
  minNotionalUsd: 5,
  maxLeverage: 5,
  minLiquidationDistanceAtr: 6,
  maxDailyLossPct: 2,
  maxConsecutiveLosses: 4,
  maxAccountDrawdownPct: 12,
  timeframes: ['5m', '15m', '30m', '1h', '2h', '4h', '1d'] as const,
  maxBarsInTrade: { '5m': 720, '15m': 240, '30m': 160, '1h': 120, '2h': 80, '4h': 48, '1d': 20 } as Record<string, number>,
  capacitySamples: 20,
  minFoldTrades: 15,
  minTestTrades: 40,
  minProfitFactor: 1.50,
  maxDrawdownPct: 12,
  maxMonteCarloLossProbability: 15,
  preOosFraction: 0.70,
  folds: 3,
  monteCarloRuns: 5000,
} as const;

export type TradingConfig = typeof TRADING_CONFIG;
export function resolveTradingConfig(overrides: Partial<TradingConfig> = {}): TradingConfig { return { ...TRADING_CONFIG, ...overrides }; }
