const DB_NAME='tradepilot-secure-wallet';const STORE='credentials';const RECORD='exchange';
interface Envelope{version:1;algorithm:'AES-256-GCM';kdf:'PBKDF2-SHA-256';iterations:number;salt:string;iv:string;ciphertext:string}
const enc=new TextEncoder(),dec=new TextDecoder();
function b64(bytes:Uint8Array){let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s)}
function bytes(s:string){const bin=atob(s);return Uint8Array.from(bin,c=>c.charCodeAt(0))}
async function derive(passphrase:string,salt:Uint8Array){const base=await crypto.subtle.importKey('raw',enc.encode(passphrase),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:600000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
export async function saveWallet(apiKey:string,apiSecret:string,passphrase:string){if(!passphrase||passphrase.length<12)throw new Error('Wallet passphrase must be at least 12 characters.');if(!apiKey||!apiSecret)throw new Error('API key and secret are required.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await derive(passphrase,salt),aad=enc.encode('tradepilot-wallet-v1'),plain=enc.encode(JSON.stringify({apiKey,apiSecret})),cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:aad},key,plain));const envelope:Envelope={version:1,algorithm:'AES-256-GCM',kdf:'PBKDF2-SHA-256',iterations:600000,salt:b64(salt),iv:b64(iv),ciphertext:b64(cipher)};const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(envelope,RECORD);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()}
export async function hasWallet(){const db=await openDb();const value=await new Promise<Envelope|null>((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get(RECORD);r.onsuccess=()=>resolve((r.result as Envelope|null)??null);r.onerror=()=>reject(r.error)});db.close();return !!value}
export async function unlockWallet(passphrase:string):Promise<{apiKey:string;apiSecret:string}>{const db=await openDb();const envelope=await new Promise<Envelope>((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get(RECORD);r.onsuccess=()=>r.result?resolve(r.result as Envelope):reject(new Error('Wallet is empty.'));r.onerror=()=>reject(r.error)});db.close();const key=await derive(passphrase,bytes(envelope.salt)),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(envelope.iv),additionalData:enc.encode('tradepilot-wallet-v1')},key,bytes(envelope.ciphertext));return JSON.parse(dec.decode(plain))}
export async function clearWallet(){const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(RECORD);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()}
