import { useEffect, useState } from 'react';
import { useApp } from '@/lib/store';
import * as api from '@/lib/api';
import { type ValidationReport } from '@/lib/backtestV11';
import { Badge, Button, Card, CardBody, CardHeader, EmptyState, LoadingState, StatCard } from '@/components/ui';

const INTERVALS = ['5m','15m','1h','4h'] as const;
type Interval = typeof INTERVALS[number];

export function AnalyticsPage(){
 const { conn, performance } = useApp();
 const [report,setReport]=useState<ValidationReport|null>(null);
 const [running,setRunning]=useState(false);
 const [error,setError]=useState<string|null>(null);
 const [elapsed,setElapsed]=useState(0);
 const [timeframe,setTimeframe]=useState<Interval>('5m');
 useEffect(()=>{if(!running)return;const started=Date.now();const id=window.setInterval(()=>setElapsed(Math.floor((Date.now()-started)/1000)),1000);return()=>window.clearInterval(id)},[running]);
 const runValidation=async()=>{if(running)return;setRunning(true);setError(null);setReport(null);setElapsed(0);try{const res=await api.validationApi('BTCUSDT',timeframe,{initialCapital:10000,feeBps:10,slippageBps:2,maxPositionPct:20,leverage:1,riskPerTradePct:.25});if(res.ok)setReport(res.data??null);else setError(res.error??'Validation failed.')}catch(e){setError(e instanceof Error?e.message:'Validation failed.')}finally{setRunning(false)}};
 if(conn==='loading'&&!performance)return <div className="p-6"><LoadingState message="Loading analytics…"/></div>;
 const funnel=report?.signalFunnel;
 const families=report?.familyPerformance?Object.entries(report.familyPerformance):[];
 return <div className="space-y-6 p-6">
  {performance?<div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><StatCard label="Equity" value={`$${performance.equity.toFixed(2)}`} tone="accent"/><StatCard label="Total PnL" value={`$${performance.total_pnl.toFixed(2)}`} tone={performance.total_pnl>=0?'positive':'negative'}/><StatCard label="Win Rate" value={`${performance.win_rate.toFixed(1)}%`}/><StatCard label="Trade Count" value={String(performance.trade_count)}/></div>:<EmptyState title="No paper results yet" message="Historical validation is independent of paper trading."/>}
  <Card><CardHeader title="Historical Validation Lab" subtitle="60,000 real Binance candles → realistic costs → v33 A+ conviction strategy → 10R–15R research targets → strict 3-fold pre-OOS gate → untouched 30% OOS → 5,000-run Monte Carlo" action={<div className="flex items-center gap-2"><label className="text-xs text-slate-400">Timeframe</label><select value={timeframe} onChange={e=>setTimeframe(e.target.value as Interval)} disabled={running} className="rounded-md border border-slate-700 bg-slate-900 px-2 py-1.5 text-xs text-slate-200">{INTERVALS.map(x=><option key={x} value={x}>{x}</option>)}</select><Button onClick={runValidation} disabled={running}>{running?`Validating… ${elapsed}s`:'Run validation'}</Button></div>}/><CardBody className="space-y-4">
   <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-lg bg-slate-800/40 p-3"><p className="text-[11px] text-slate-500">Data</p><p className="text-sm font-semibold">BTCUSDT · {timeframe} · 60,000 candles</p></div><div className="rounded-lg bg-slate-800/40 p-3"><p className="text-[11px] text-slate-500">Strategy</p><p className="text-sm font-semibold text-sky-300">Production Regime Breakout v33</p><p className="mt-1 text-[11px] text-slate-500">A+ score ≥96, structural stop, historical path-capacity filter, 10R target and 15R only for score ≥99.</p></div><div className="rounded-lg bg-slate-800/40 p-3"><p className="text-[11px] text-slate-500">Fee</p><p className="text-sm font-semibold">10 bps/side</p></div><div className="rounded-lg bg-slate-800/40 p-3"><p className="text-[11px] text-slate-500">Slippage</p><p className="text-sm font-semibold">2 bps/side</p></div></div>
   <div className="rounded-lg border border-sky-900/50 bg-sky-950/20 px-4 py-3 text-xs text-slate-300">The validation gate is unchanged. Every pre-OOS fold must meet minimum trades, positive return, PF ≥ 1.05 and DD ≤ 20%. OOS is not run unless all folds pass.</div>
   {running&&<div className="rounded-lg border border-sky-800/60 bg-sky-950/30 px-4 py-3 text-xs text-sky-200">Running v33 with real OHLC candles, fees and slippage. Keep the bot stopped while this completes.</div>}
   {error&&<div className="rounded-lg bg-red-950/40 px-3 py-2 text-xs text-red-300">{error}</div>}
   {report&&<>
    <div className={`rounded-lg border px-4 py-3 ${report.gate.status==='VALIDATED'?'border-emerald-800 bg-emerald-950/30':'border-red-800 bg-red-950/30'}`}><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide">Paper-trading gate</p><p className="mt-1 text-lg font-bold">{report.gate.status}</p></div><Badge tone={report.gate.status==='VALIDATED'?'positive':'negative'}>{report.gate.status==='VALIDATED'?'READY FOR PAPER':'DO NOT TRADE'}</Badge></div>{report.gate.reasons.length>0&&<ul className="mt-2 list-disc space-y-1 pl-5 text-xs text-red-200">{report.gate.reasons.map((x,i)=><li key={i}>{x}</li>)}</ul>}</div>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><div className="rounded-lg border border-slate-800 p-3"><p className="text-[11px] text-slate-500">Historical candles</p><p className="text-sm font-semibold">{report.candles.toLocaleString()}</p></div><div className="rounded-lg border border-slate-800 p-3"><p className="text-[11px] text-slate-500">History span</p><p className="text-sm font-semibold">{report.dataQuality.durationDays.toFixed(1)} days</p></div><div className="rounded-lg border border-slate-800 p-3"><p className="text-[11px] text-slate-500">Data gaps</p><p className="text-sm font-semibold">{report.dataQuality.gaps}</p></div><div className="rounded-lg border border-slate-800 p-3"><p className="text-[11px] text-slate-500">Monte Carlo runs</p><p className="text-sm font-semibold">{report.monteCarlo.simulations.toLocaleString()}</p></div></div>
    <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-slate-500"><tr><th className="px-2 py-2">Strategy</th><th>Trades</th><th>Win %</th><th>PF</th><th>Return</th><th>Max DD</th></tr></thead><tbody>{report.strategies.map(s=><tr key={s.id} className="border-t border-slate-800"><td className="px-2 py-2 font-medium">{s.name}</td><td>{s.trades}</td><td>{s.winRate.toFixed(1)}%</td><td>{s.profitFactor.toFixed(2)}</td><td className={s.returnPct>=0?'text-emerald-400':'text-red-400'}>{s.returnPct.toFixed(2)}%</td><td>{s.maxDrawdownPct.toFixed(2)}%</td></tr>)}</tbody></table></div>
    {funnel&&<div className="rounded-lg border border-slate-800 p-4"><p className="mb-3 text-xs font-semibold">Signal funnel diagnostics</p><div className="grid grid-cols-2 gap-3 md:grid-cols-5">{[['Bars evaluated',funnel.barsEvaluated],['No local pattern',funnel.noLocalPattern],['Momentum rejected',funnel.rejectedMomentum],['HTF rejected',funnel.rejectedHtf],['Score rejected',funnel.rejectedScore],['Structural stop rejected',funnel.rejectedStructuralStop],['Risk floor rejected',funnel.rejectedRiskFloor],['Path capacity rejected',funnel.rejectedPathCapacity],['Signals opened',funnel.tradesOpened]].map(([k,v])=><div key={String(k)}><p className="text-[11px] text-slate-500">{k}</p><p className="text-sm font-semibold">{Number(v).toLocaleString()}</p></div>)}</div></div>}
    {families.length>0&&<div className="rounded-lg border border-slate-800 p-4"><p className="mb-3 text-xs font-semibold">Strategy-family performance</p><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-slate-500"><tr><th className="px-2 py-2">Family</th><th>Trades</th><th>Win %</th><th>PF</th><th>Return</th></tr></thead><tbody>{families.map(([family,s])=><tr key={family} className="border-t border-slate-800"><td className="px-2 py-2 capitalize">{family}</td><td>{s.trades}</td><td>{s.winRate.toFixed(1)}%</td><td>{s.profitFactor.toFixed(2)}</td><td>{s.returnPct.toFixed(2)}%</td></tr>)}</tbody></table></div></div>}
    <div className="grid grid-cols-1 gap-3 md:grid-cols-4"><div className="rounded-lg border border-slate-800 p-3"><p className="text-[11px] text-slate-500">Pre-OOS folds</p><p className="text-sm font-semibold">{report.walkForward.trainBars} / {report.walkForward.validationBars} / {report.walkForward.testBars}</p></div><div className="rounded-lg border border-slate-800 p-3"><p className="text-[11px] text-slate-500">Selected strategy</p><p className="text-sm font-semibold">{report.walkForward.selectedStrategy}</p></div><div className="rounded-lg border border-slate-800 p-3"><p className="text-[11px] text-slate-500">OOS result</p><p className="text-sm font-semibold">{report.walkForward.test?`${report.walkForward.test.returnPct.toFixed(2)}% · PF ${report.walkForward.test.profitFactor.toFixed(2)} · ${report.walkForward.test.trades} trades`:'Not run until all folds pass'}</p></div><div className="rounded-lg border border-slate-800 p-3"><p className="text-[11px] text-slate-500">MC loss probability</p><p className="text-sm font-semibold">{report.monteCarlo.probabilityOfLoss.toFixed(1)}%</p></div></div>
   </>}
  </CardBody></Card>
 </div>;
}
