import { useEffect,useState } from 'react';
import { Lock,AlertTriangle,RotateCcw,ShieldCheck,KeyRound,Trash2 } from 'lucide-react';
import { useApp } from '@/lib/store';import * as api from '@/lib/api';import { hasWallet,saveWallet,clearWallet } from '@/lib/wallet';
import { Badge,Button,Card,CardBody,CardHeader,LoadingState } from '@/components/ui';import type { RiskLevel,ThemeMode } from '@/lib/types';
export function SettingsPage(){const{settings,account,refresh}=useApp();const[saving,setSaving]=useState(false),[resetting,setResetting]=useState(false),[resetMsg,setResetMsg]=useState<string|null>(null),[walletReady,setWalletReady]=useState(false),[apiKey,setApiKey]=useState(''),[apiSecret,setApiSecret]=useState(''),[passphrase,setPassphrase]=useState(''),[walletMsg,setWalletMsg]=useState<string|null>(null),[walletBusy,setWalletBusy]=useState(false);useEffect(()=>{hasWallet().then(setWalletReady).catch(()=>setWalletReady(false))},[]);if(!settings)return <div className="p-6"><LoadingState message="Loading settings…"/></div>;
 const update=async(patch:Partial<typeof settings>)=>{setSaving(true);await api.updateSettingsApi(patch);await refresh();setSaving(false)};
 const handleReset=async()=>{setResetting(true);setResetMsg(null);const r=await api.resetApi();setResetMsg(r.ok?r.data?.message??'Account reset.':r.error??'Reset failed.');await refresh();setResetting(false)};
 const storeWallet=async()=>{setWalletBusy(true);setWalletMsg(null);try{await saveWallet(apiKey.trim(),apiSecret,passphrase);setWalletReady(true);setApiKey('');setApiSecret('');setPassphrase('');setWalletMsg('Encrypted wallet saved. Secret is never displayed or stored in the trading database.')}catch(e){setWalletMsg(e instanceof Error?e.message:'Wallet save failed.')}finally{setWalletBusy(false)}};
 const removeWallet=async()=>{setWalletBusy(true);await clearWallet();setWalletReady(false);setWalletMsg('Encrypted wallet removed from this browser.');setWalletBusy(false)};
 const paused=account?.bot_status==='PAUSED';
 return <div className="mx-auto max-w-3xl space-y-6 p-6">
  <Card><CardHeader title="Trading Mode" subtitle="Paper trading only until a separately authenticated live execution service is enabled."/><CardBody className="space-y-3"><div className="flex items-center justify-between rounded-lg border border-emerald-800 bg-emerald-950/40 px-4 py-3"><div><p className="text-sm font-semibold text-emerald-400">PAPER TRADING</p><p className="text-xs text-slate-500">Active — simulated execution</p></div><Badge tone="positive">Active</Badge></div>{paused&&<div className="rounded-lg border border-amber-700 bg-amber-950/40 px-4 py-3 text-xs text-amber-300"><b>CAPITAL PROTECTION PAUSE</b><div className="mt-1">{account?.pause_reason??'Loss limit reached.'} {account?.pause_until&&<>Resume after {new Date(account.pause_until).toLocaleString()}.</>}</div></div>}</CardBody></Card>
  <Card><CardHeader title="Secure Exchange Wallet" subtitle="AES-256-GCM encrypted browser vault. The plaintext secret never enters PGlite or GitHub."/><CardBody className="space-y-4"><div className="flex items-center justify-between rounded-lg border border-sky-800 bg-sky-950/30 px-4 py-3"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-sky-400"/><span className="text-sm text-slate-300">{walletReady?'Encrypted wallet configured':'No encrypted wallet configured'}</span></div><Badge tone={walletReady?'positive':'neutral'}>{walletReady?'AES-256-GCM':'Empty'}</Badge></div><div className="grid gap-3 sm:grid-cols-2"><input value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="Exchange API key" autoComplete="off" className="rounded-lg border border-slate-700 bg-slate-800/50 px-3 py-2 text-sm"/><input value={apiSecret} onChange={e=>setApiSecret(e.target.value)} placeholder="Exchange API secret" type="password" autoComplete="new-password" className="rounded-lg border border-slate-700 bg-slate-800/50 px-3 py-2 text-sm"/></div><div className="flex gap-2"><input value={passphrase} onChange={e=>setPassphrase(e.target.value)} placeholder="Wallet passphrase (12+ chars)" type="password" autoComplete="new-password" className="flex-1 rounded-lg border border-slate-700 bg-slate-800/50 px-3 py-2 text-sm"/><Button onClick={storeWallet} disabled={walletBusy||!apiKey||!apiSecret||passphrase.length<12}><KeyRound className="h-4 w-4"/>Encrypt & Store</Button></div>{walletReady&&<Button variant="danger" onClick={removeWallet} disabled={walletBusy}><Trash2 className="h-4 w-4"/>Remove Wallet</Button>}{walletMsg&&<p className="text-xs text-slate-400">{walletMsg}</p>}<div className="rounded-lg bg-slate-800/40 px-4 py-3 text-xs text-slate-400"><b className="text-slate-300">Withdrawal firewall:</b> TradePilot has no withdrawal operation. Configure the exchange key with trading/read permissions only and disable withdrawals at the exchange. The app must reject any future withdrawal route.</div></CardBody></Card>
  <Card><CardHeader title="Hard Risk Limits" subtitle="These are enforced in the engine and repository layer, not only in the UI."/><CardBody className="space-y-5"><div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><label className="text-xs text-slate-400">Max positions<input type="range" min="1" max="20" step="1" value={settings.max_positions} onChange={e=>update({max_positions:Number(e.target.value)})} disabled={saving} className="mt-2 w-full"/><span className="font-semibold text-sky-400">{settings.max_positions} / 20</span></label><label className="text-xs text-slate-400">Max strategies<input type="range" min="1" max="10" step="1" value={settings.max_strategies} onChange={e=>update({max_strategies:Number(e.target.value)})} disabled={saving} className="mt-2 w-full"/><span className="font-semibold text-sky-400">{settings.max_strategies} / 10</span></label><label className="text-xs text-slate-400">Max leverage<input type="range" min="1" max="10" step="1" value={settings.max_leverage} onChange={e=>update({max_leverage:Number(e.target.value),leverage:Math.min(settings.leverage,Number(e.target.value))})} disabled={saving} className="mt-2 w-full"/><span className="font-semibold text-sky-400">{settings.max_leverage}x / 10x</span></label></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><label className="text-xs text-slate-400">Active leverage<input type="range" min="1" max={settings.max_leverage} step="1" value={Math.min(settings.leverage,settings.max_leverage)} onChange={e=>update({leverage:Number(e.target.value)})} disabled={saving} className="mt-2 w-full"/><span className="font-semibold text-sky-400">{settings.leverage}x</span></label><div className="rounded-lg border border-slate-700 bg-slate-800/30 p-3"><p className="text-xs text-slate-400">Capital ceiling</p><p className="mt-1 text-sm font-semibold text-emerald-400">UNLIMITED</p><p className="mt-1 text-[11px] text-slate-500">No artificial portfolio ceiling. Actual buying power remains constrained by equity, margin and the 10x hard leverage limit.</p></div></div></CardBody></Card>
  <Card><CardHeader title="Capital Protection" subtitle="Automatic kill-switch: close positions and pause the engine for 24 hours when the loss limit is reached."/><CardBody className="space-y-4"><label className="block text-xs text-slate-400">Session loss limit<input type="range" min="0.25" max="10" step="0.25" value={settings.loss_limit_pct} onChange={e=>update({loss_limit_pct:Number(e.target.value)})} disabled={saving} className="mt-2 w-full"/><span className="font-semibold text-red-400">{settings.loss_limit_pct.toFixed(2)}%</span></label><div className="flex items-center justify-between rounded-lg border border-amber-800 bg-amber-950/30 px-4 py-3"><span className="text-sm text-slate-300">Automatic pause duration</span><b className="text-amber-300">24 HOURS</b></div></CardBody></Card>
  <Card><CardHeader title="Signal Quality" subtitle="Higher threshold = fewer, more selective entries."/><CardBody><div className="flex items-center gap-4"><input type="range" min="60" max="95" step="1" value={settings.confidence_threshold_pct} onChange={e=>update({confidence_threshold_pct:Number(e.target.value)})} disabled={saving} className="flex-1"/><span className="w-16 text-right text-sm font-semibold text-sky-400">{settings.confidence_threshold_pct}%</span></div><p className="mt-2 text-xs text-slate-500">The strategy now uses trend alignment, momentum, RSI extension control, structural break/reclaim, volatility regime and up to 10 strategy profiles.</p></CardBody></Card>
  <Card><CardHeader title="Risk Level"/><CardBody><div className="grid grid-cols-3 gap-2">{(['Conservative','Balanced','Aggressive'] as RiskLevel[]).map(r=><button key={r} onClick={()=>update({risk_level:r})} disabled={saving} className={`rounded-lg px-3 py-2.5 text-sm font-medium ${settings.risk_level===r?'bg-sky-600 text-white':'bg-slate-800 text-slate-400'}`}>{r}</button>)}</div></CardBody></Card>
  <div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Card><CardHeader title="Stop Loss"/><CardBody><input type="range" min="0.5" max="10" step="0.5" value={settings.stop_loss_pct} onChange={e=>update({stop_loss_pct:Number(e.target.value)})} className="w-full"/><span className="text-sm font-semibold text-red-400">{settings.stop_loss_pct}%</span></CardBody></Card><Card><CardHeader title="Take Profit"/><CardBody><input type="range" min="1" max="20" step="0.5" value={settings.take_profit_pct} onChange={e=>update({take_profit_pct:Number(e.target.value)})} className="w-full"/><span className="text-sm font-semibold text-emerald-400">{settings.take_profit_pct}%</span></CardBody></Card></div>
  <Card><CardHeader title="Theme"/><CardBody><div className="grid grid-cols-3 gap-2">{(['Dark','Light','System'] as ThemeMode[]).map(t=><button key={t} onClick={()=>update({theme:t})} disabled={saving} className={`rounded-lg px-3 py-2.5 text-sm font-medium ${settings.theme===t?'bg-sky-600 text-white':'bg-slate-800 text-slate-400'}`}>{t}</button>)}</div></CardBody></Card>
  <Card><CardHeader title="Notifications"/><CardBody className="space-y-3">{([{key:'trade_alerts' as const,label:'Trade Alerts'},{key:'pnl_alerts' as const,label:'PnL Updates'},{key:'risk_alerts' as const,label:'Risk Alerts'}]).map(x=><label key={x.key} className="flex items-center justify-between rounded-lg bg-slate-800/40 px-4 py-3"><span className="text-sm text-slate-300">{x.label}</span><button onClick={()=>update({[x.key]:!settings[x.key]} as Partial<typeof settings>)} disabled={saving} className={`relative h-6 w-11 rounded-full ${settings[x.key]?'bg-sky-600':'bg-slate-700'}`}><span className={`absolute top-0.5 h-5 w-5 rounded-full bg-white ${settings[x.key]?'translate-x-5':'translate-x-0.5'}`}/></button></label>)}</CardBody></Card>
  <Card><CardHeader title="Development Reset" subtitle="Reset paper account and clear trading history"/><CardBody><div className="flex items-center gap-3"><Button variant="danger" onClick={handleReset} disabled={resetting}><RotateCcw className="h-4 w-4"/>Reset Account</Button>{resetMsg&&<span className="text-xs text-slate-400">{resetMsg}</span>}</div><div className="mt-3 flex items-start gap-2 rounded-lg bg-amber-950/40 px-3 py-2 text-xs text-amber-400"><AlertTriangle className="mt-0.5 h-3.5 w-3.5"/>This clears all paper positions, trades and snapshots.</div></CardBody></Card>
 </div>}
