import { useState } from 'react';
import { AlertTriangle, RotateCcw, ShieldCheck } from 'lucide-react';
import { useApp } from '@/lib/store';
import * as api from '@/lib/api';
import { TRADING_CONFIG } from '@/lib/tradingConfig';
import { Badge, Button, Card, CardBody, CardHeader, LoadingState } from '@/components/ui';
import type { RiskLevel, ThemeMode } from '@/lib/types';

export function SettingsPage(){
 const{settings,refresh}=useApp();const[saving,setSaving]=useState(false),[resetting,setResetting]=useState(false),[resetMsg,setResetMsg]=useState<string|null>(null);
 if(!settings)return <div className="p-6"><LoadingState message="Loading settings…"/></div>;
 const update=async(patch:Partial<typeof settings>)=>{setSaving(true);await api.updateSettingsApi(patch);await refresh();setSaving(false);};
 const reset=async()=>{setResetting(true);setResetMsg(null);const r=await api.resetApi();setResetMsg(r.ok?(r.data?.message??'Account reset.'):r.error??'Reset failed.');await refresh();setResetting(false);};
 return <div className="mx-auto max-w-3xl space-y-6 p-6">
  <Card><CardHeader title="Trading Mode" subtitle="v36 remains paper-only until the current validation gate passes."/><CardBody className="space-y-3"><div className="flex items-center justify-between rounded-lg border border-emerald-800 bg-emerald-950/40 px-4 py-3"><div><p className="text-sm font-semibold text-emerald-400">PAPER TRADING</p><p className="text-xs text-slate-500">Real completed Binance candles; simulated fills only.</p></div><Badge tone="positive">Active</Badge></div><p className="text-xs text-slate-500">Live execution is intentionally unavailable. A rejected validation gate cannot be bypassed from Settings.</p></CardBody></Card>
  <Card><CardHeader title="Small-Account Guardrails" subtitle={`Designed around a $${TRADING_CONFIG.paperStartingCapital} starting paper account.`}/><CardBody className="space-y-4"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Capital',`$${TRADING_CONFIG.paperStartingCapital}`],['Max Position',`${settings.max_allocation_pct}%`],['Max Leverage',`${settings.leverage}x`],['Max Positions',String(TRADING_CONFIG.maxPositions)]].map(([l,v])=><div key={l} className="rounded-lg bg-slate-800/40 p-3"><p className="text-[11px] text-slate-500">{l}</p><p className="mt-1 text-sm font-semibold text-slate-200">{v}</p></div>)}</div><div className="rounded-lg border border-emerald-900 bg-emerald-950/30 px-3 py-2 text-xs text-emerald-300"><ShieldCheck className="mr-1 inline h-3.5 w-3.5"/>Risk sizing includes fees/slippage, minimum notional, leverage and liquidation-distance checks. Daily loss, consecutive-loss and account-drawdown locks fail closed.</div><div className="flex items-center gap-4"><label className="w-36 text-xs text-slate-400">Leverage</label><input type="range" min={1} max={TRADING_CONFIG.maxLeverage} step={1} value={settings.leverage} onChange={e=>update({leverage:Number(e.target.value)})} disabled={saving} className="flex-1"/><span className="w-12 text-right text-sm font-semibold">{settings.leverage}x</span></div><div className="flex items-center gap-4"><label className="w-36 text-xs text-slate-400">Daily loss</label><input type="range" min={0.25} max={TRADING_CONFIG.maxDailyLossPct} step={0.25} value={settings.loss_limit_pct} onChange={e=>update({loss_limit_pct:Number(e.target.value)})} disabled={saving} className="flex-1"/><span className="w-12 text-right text-sm font-semibold">{settings.loss_limit_pct}%</span></div><div className="flex items-center gap-4"><label className="w-36 text-xs text-slate-400">Max allocation</label><input type="range" min={1} max={TRADING_CONFIG.maxAllocationPct} step={1} value={settings.max_allocation_pct} onChange={e=>update({max_allocation_pct:Number(e.target.value)})} disabled={saving} className="flex-1"/><span className="w-12 text-right text-sm font-semibold">{settings.max_allocation_pct}%</span></div></CardBody></Card>
  <Card><CardHeader title="Risk Level" subtitle="Changes sizing preference; never bypasses hard strategy gates."/><CardBody><div className="grid grid-cols-3 gap-2">{(['Conservative','Balanced','Aggressive'] as RiskLevel[]).map(r=><button key={r} onClick={()=>update({risk_level:r})} disabled={saving} className={`rounded-lg px-3 py-2.5 text-sm font-medium ${settings.risk_level===r?'bg-sky-600 text-white':'bg-slate-800 text-slate-400'}`}>{r}</button>)}</div></CardBody></Card>
  <Card><CardHeader title="Minimum Score" subtitle={`v36 base threshold ${TRADING_CONFIG.minScore}; ultra conviction ${TRADING_CONFIG.ultraScore}.`}/><CardBody className="space-y-3"><div className="flex items-center gap-4"><input type="range" min={TRADING_CONFIG.minScore} max={95} step={1} value={settings.confidence_threshold_pct} onChange={e=>update({confidence_threshold_pct:Number(e.target.value)})} disabled={saving} className="flex-1"/><span className="w-16 text-right text-sm font-semibold">{settings.confidence_threshold_pct}</span></div><p className="text-xs text-slate-500">This is only an entry-quality preference. Dynamic target feasibility and the validation gate remain mandatory.</p></CardBody></Card>
  <Card><CardHeader title="Cost Model" subtitle="Every validation and paper trade includes both costs."/><CardBody><div className="grid grid-cols-2 gap-3"><div className="rounded-lg bg-slate-800/40 p-3"><p className="text-[11px] text-slate-500">Fee</p><p className="text-sm font-semibold">{settings.fee_bps} bps/side</p></div><div className="rounded-lg bg-slate-800/40 p-3"><p className="text-[11px] text-slate-500">Slippage</p><p className="text-sm font-semibold">{settings.slippage_bps} bps/side</p></div></div></CardBody></Card>
  <Card><CardHeader title="Theme"/><CardBody><div className="grid grid-cols-3 gap-2">{(['Dark','Light','System'] as ThemeMode[]).map(t=><button key={t} onClick={()=>update({theme:t})} disabled={saving} className={`rounded-lg px-3 py-2.5 text-sm font-medium ${settings.theme===t?'bg-sky-600 text-white':'bg-slate-800 text-slate-400'}`}>{t}</button>)}</div></CardBody></Card>
  <Card><CardHeader title="Notifications"/><CardBody className="space-y-3">{[{key:'trade_alerts' as const,label:'Trade Alerts'},{key:'pnl_alerts' as const,label:'PnL Updates'},{key:'risk_alerts' as const,label:'Risk Alerts'}].map(x=><label key={x.key} className="flex items-center justify-between rounded-lg bg-slate-800/40 px-4 py-3"><span className="text-sm text-slate-300">{x.label}</span><button onClick={()=>update({[x.key]:!settings[x.key]} as Partial<typeof settings>)} disabled={saving} className={`h-6 w-11 rounded-full ${settings[x.key]?'bg-sky-600':'bg-slate-700'}`}><span className="sr-only">toggle</span></button></label>)}</CardBody></Card>
  <Card><CardHeader title="Development Reset" subtitle={`Clear paper history and restore the $${TRADING_CONFIG.paperStartingCapital} starting account.`}/><CardBody><div className="flex items-center gap-3"><Button variant="danger" onClick={reset} disabled={resetting}><RotateCcw className="h-4 w-4"/>Reset Account</Button>{resetMsg&&<span className="text-xs text-slate-400">{resetMsg}</span>}</div><div className="mt-3 flex items-start gap-2 rounded-lg bg-amber-950/40 px-3 py-2 text-xs text-amber-400"><AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0"/><span>This clears positions, trades and snapshots. It does not create or store exchange credentials.</span></div></CardBody></Card>
 </div>;
}
